### ISSUE TITLE
Decryption error - too few arguments passed to decryptUsingKey

### ISSUE THREAD

**Issue by nicholasbulka** [web-token/jwt-framework#109]
Receiving Fatal error: Uncaught ArgumentCountError: Too few arguments to function Jose\Component\Encryption\JWEDecrypter::decryptUsingKey(), 2 passed in  ... expecting 3.

I am using the example listed on this page.
https://web-token.spomky-labs.com/component/jwe/loading.html
Error occurs here:
$jwe = $jweDecrypter->decryptUsingKey($jwe, $jwk);

The source code looks like it expects a $recipient integer parameter, but I have no idea what to put for this.

Thanks!

**Comment by Spomky** [comment]
It looks like the documentation is not in line with the library.
I will update it.

In some cases the JWE object may be designed for several recipients (see https://web-token.spomky-labs.com/advanced/jwe/multiple_recipients.html).
The `$recipient` argument corresponds to the recipient index in the JWE object.

To check if you have more than one recipient, you can use the `->count()` method or call `count($jwe)`.
If you have only one recipient, just set `0` as third argument.

**Comment by Spomky** [comment]
Closing as answered.
Feel free to reopen or comment if you need other details.

Regards.
