### ISSUE TITLE
How do I use this library?

### ISSUE THREAD

**Issue by ghola** [web-token/jwt-framework#115]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.0.78

I'm trying to use this library with Symfony 4 to enable JWT based authentication. I installed the bundle using `composer require web-token/jwt-bundle` as per the [documentation](https://web-token.spomky-labs.com/bundle/), but beyond that I have absolutely no clue how to use it. I looked through the bundle code and saw a lot of console commands in there. I expected them to appear as you run `bin/console`, but no such luck.

There is nothing in the documentation about JWTs (not even how to create or validate one), no details about the services made available by the bundle or a configuration reference in the vein of how other bundles have. (e.g. [doctrine](https://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html)).

So at this point I'm just going to move on and use [this bundle](https://github.com/lexik/LexikJWTAuthenticationBundle) instead (which seems to depend on an older version of this library).

**Comment by Spomky** [comment]
Hi,

First of all, he purpose if this framework and the LexikJWTAuthenticationBundle are not the same.

The LexikJWTAuthenticationBundle is a bundle that provides a firewall to protect an API. The authentication of the users is based on JWT.
This one will help you to manage your keys, key sets or load/issue signed or encrypted tokens. It is supposed to be used by other bundles/applications such as LexikJWTAuthenticationBundle (e.g. [spomky-labs/lexik-jose-bridge](https://github.com/Spomky-Labs/lexik-jose-bridge)).

There is no concept of user/firewall/authentication... It can be used to create a secured instant messaging as well as an identity provider (OpenId Connect) or whatever you want that requires confidentiality or non-repudiation of the data.

Regarding the bundle, the documentation may be not clear about that, but the `capabilities will depend on the components installed in your application`.
If your application needs
* to check claims or headers, you will need the `web-token/jwt-checker` component
* to sign/verify tokens, you will need the `web-token/jwt-signature` component
* to encrypt/decrypt tokens, you will need the `web-token/jwt-encryption` component
* to manage keys/key sets, you will need the `web-token/jwt-key-mgmt` component
* to use console commands, you will need the `web-token/jwt-console` component

In any case, you are right to say that a should wrote a list of the services made available by the bundle or the whole configuration reference. I will do it within the next weeks.

**Comment by ghola** [comment]
Thank you for the reply and clarifications. Now I have a much better understanding on the purpose of this library.

**Comment by Spomky** [comment]
Closing as answered.
The documentation is improved step by step.
Feel free to re-open if needed.

**Comment by juanm18** [comment]
I have ran into issues when attempting to use this library as well. I am looking to use the JWE bundle i have installed it like shown in documentation `composer require web-token/jwt-encryption`.. When i try to create a token i get an error: `Fatal error: Uncaught Error: Call to private Jose\Component\Core\AlgorithmManager::__construct() from invalid context in /Volumes/Source/authserver/asp.php:14
Stack trace:
#0 {main}`
any idea as to why i am running into this error? I know this issue is closed but did not want to open a new one for same issue

**Comment by Spomky** [comment]
Hi @juanm18,

Please see https://github.com/web-token/jwt-doc/issues/11
The doc is now in line with the v1.0
