### ISSUE TITLE
why jws not allow RSA & ES256?

### ISSUE THREAD

**Issue by lovearthhome** [web-token/jwt-framework#122]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Version              | latest

![_20180515153610](https://user-images.githubusercontent.com/16535358/40043002-bcac2b9c-5855-11e8-8737-e941dbf51bc8.png)
jws will Exception as follows when deal with RSA & ES256.

ECDSA only allow "EC" type.
now what to do ?

`
Type: InvalidArgumentException
Message: Wrong key type.
File: ./jwt_framework/jwt-signature/vendor/web-token/jwt-signature/Algorithm/ECDSA.php
Line: 92
`

**Comment by Spomky** [comment]
* RSA key type is for RSA algorithms (RSxxx or PSxxx).
* EC key type is for EC algorithm (ESxxx).

**Comment by lovearthhome** [comment]
@Spomky  We had solved the problem using jwt-framework in a very funny way. 
we use `AlgorithmIdentifiers.ECDSA_USING_P256_CURVE_AND_SHA256(java code)` to generate public/private key in such a format. 
`
public key(private key is similar format: RSA & ES256)
{"kty":"RSA","kid":"***","alg":"ES256","n":"***","e":"AQAB"}
`
now is the miracle time:

1: we change the ES256 to RS256 in thre private key, 
2: change algorithm from ES256 -> RS256 in the php code.
3. The generated token is verified true by the ES256 public key .

this is interesting. Other develepers have the same expierence. and We agree this is a bug for jwt-framework.

**Comment by Spomky** [comment]
Hi,

That a good news. However I am still convinced there is a problem with the result of `AlgorithmIdentifiers.ECDSA_USING_P256_CURVE_AND_SHA256(java code)`.

This lines clearly refers to an EC key on the P-256 curve, but the key you mention has [RSA components](https://tools.ietf.org/html/rfc7518#section-6.3) (namely `n`, `e` and for your private key at least `d` and maybe `p`, `q`, `dq`, `dp` or `qi`).

[EC key components](https://tools.ietf.org/html/rfc7518#section-6.2) are `crv`, `x`, `y` and for your private key `d`.

So for me `lgorithmIdentifiers.ECDSA_USING_P256_CURVE_AND_SHA256(java code)` produces RSA keys, not EC ones.
I can see the [same confusion here](https://www.alibabacloud.com/help/doc-detail/48019.htm).
In the given example `{"kty":"RSA","kid":"88483727556929326703309904351185815489","alg":"ES256","n":"ie0IKv...8dYAFAVEFsvXCFvdaxQefwWFw","e":"AQAB"}`
we can clearly see that the type is `RSA` (`kty` and presence of `n` and `e` parameters) but the associated algorithm is `ES256` (an EC algorithm) which is technically impossible.
It would be interesting to contact the developer of that Java implementation to confirm or deny my assumption.

Anyway, I am happy to know that you solved that issue.
I now close it. Feel free to re-open it needed.

**Comment by dzmitry-kankalovich** [comment]
Funnily enough, I ran into the same behavior with the [JS JWT lib](https://stackoverflow.com/questions/68905819/why-ec-key-is-treated-as-a-valid-rsa-key-for-the-jwt-and-jwk). This might be not a language-specific thing.

**Comment by Spomky** [comment]
Hi,

As I mentioned before, this is not a behavior of one library or the other, but the way the key is created that is not correct.
