### ISSUE TITLE
error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length

### ISSUE THREAD

**Issue by mwleinad** [web-token/jwt-framework#138]
| Q                    | A
| -------------------- | -----
| Bug report?          | Yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Version              | x.y(.z)

For the life of me I can't figure out what's going on. I can't decode my payload

Here's my code
https://pastebin.com/fKdVg3qP

Here's the payload
https://pastebin.com/jsjCrRrQ

Am I missing something? Is maybe my SSL version corrupted?

Thanks

**Comment by Spomky** [comment]
Hi,

I tried to decrypt the token with the given key, but it fails also on my platform.
The key looks invalid.
How is that JWE computed?

**Comment by mwleinad** [comment]
Ok, I found one error
$key = 'JdbnTFijRYcOJ0rg4CFnl2KnPSHJ1FaJbP6H30rIAB_asozaEDz4iRh4rZFmZDNR'; //New working secret.
//$key = hash('sha256', $key); < I was using this, but this hash was different from a ruby example that I have working
$key = openssl_digest( $key , 'sha256', true); // I'm doing this now, which matches the ruby hash

However now I get a CEK Unable to decrypt or to verify the tag 
:(

here's a new payload
eyJhbGciOiJBMjU2R0NNS1ciLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJnaExrcWJwdlZtNW9VanprIiwidGFnIjoiMUpFOEZGdGZlZzNGSGRMeFNXZUx4QSJ9.b4F3UtiJ4Ngkptjlz0oQjXw9UJcD4f5fnKdwSVrisk8.r0GC8Wo9Oy_8BUCI.RUV0gKLlH7hiFIjr8K6c2gc00lxzqW_blxVDgRUUh_Ve_T8Ff7WGMfgrb8mLX2QEOupCOaPo-xzrYmwjtWmPxUf3WGaRDtKc5yGslKfpI8xv0p2T5IfIG2vaBqCGmNthM955DpCjFEtSlzHV3yw6qbYO3nWM646TeE0rCgYjIkJtFH4z8brDTxdhuhps0RvmWfjVWBQWdaHYL6vfciJcfrUc9iUGJNY16qA14PuNBOR32i2iG7N_W_z0HlDcJQUatyn--plnDJ3Kle9IpURVsReZc1Tn-DM-MpeGyCufHoIZ6QKgtLx4tpBAhD7_k9HIl9Ltx6bGp_UHyZLspYDLIW5VESLRjoA9_Lz5NnFegoDRVqWzdjOI0ZhKj2NmP_cu3SFUe7cNkGhOZV9Al_NgwPE-5IItQt69QZcTD1TfF8aAafOL7VMqDpjEFG3UzVAs9u4KW18-HlCUfEl5pXEnkAQf3hy8s1eFGF3JV6ilFnHzrqvrJd8FBp3TE_6536OBI8FkwKPiwqbOVcPZajBHloctRoYNMU9YR-6VoCoh3krM7J01JM5bGD0imL8SvUpqM6KrN1_lW7_1xmT4muvwduNYJk9mkDwtRJXZrz6pa5H1G3f3BJMWmB5pi8A3LHNxg8EgqVdZIdaI0BnXgaHFk3ZcBMGLXjhS1JBnTbjJSFLZLT7b0jeqM6gd2ocdZ4JGs57TzzA4CFR8ccKohLGuFgJvBqYcqR3k81GfqNgFJ-EkrqftvjMM5nVX1XIT2qYkwyqWxdglXUURGd5Xa-VhJ8n1b4T8FXfusWk-LYCPIwVyk9FUNyas3vLwplXpqjWdeiUQuSUQUNi4hsGZhsQuqMAPGf23YeAhDahNFh3WSNepkeU28DCW8eBxTRxKdNsOX8FihWp5kkQal9w32qpn7mcTFjpRW3PxvgnOGBW3dw1gd0DoUvpQRurhXxqyA6XtU3OuiDwjbP4Z7n-VJnihYspRd3-yvLXjcA16ERaSseGymETujv7MeRORikbJRx2dlom_79K34qc16HhX8H0LUFPA4fttijTzI9ulQVjSEo3aMd4DHpSGWw5IxylXhV_uMsaCyCYnFN9XkSEzdxpB4AkI6fCbGzmMmsxPoaOwVlglJeEbFsH9e2r4Q83DymLpS2tk3uA3IEZNLxmygUem78eqjGh34g8j4VgpPiIk8GG-HWRHdtoyEKJAUTHztS8qvm7Fsv_bPV16gu8fGoQ1YwS1SenvYTk9KBGqVX5QMSNnyPU5LNHYCOPB1LC4GJBamZrhVzZxzLidX0NMqhYvNOvjrZhneyDnj4Kur1g0T9Qqj8zD27KLcCdnVXKgw3VXRgJj5KqhcraXy6V43Lx6yotWExUVLGtTCK6BjuW9i91Bx3N7APCWAlxX65hjj3gt3Z1TVW7kjs2mLh-yjGUzyUDCXns2mfu4XlRTJHahc4f2q4NYiovddrB4T0NW8oieunSQwwvnh7I6DURWP0wmVsobp1cb8XfZKFLCRyVoI6xtdXqB8tv0DSA5B8FNwSJt-7xsfrB2UHQMzKQyAN_MSSpuN-xqwzhYhmhP7kvkoTRt4z2st4tjwwW4nt8K2zTbU7t5kdC3bIf3m5twUEQda8FEuIpmdXA1_MTLQorFhAjZqXotCwbNAM9N0-N7lEZmJK5LeovsxmONp9PIrA_1uZ-4m8NO3Ij32hXzvas_dzTHeqLzvtx882AhsTXardAIwyEnKFUYRCMWW6WQV-vEdbJI2VdyHSStoqt6lQ.N-Ji_j2_8hUh4tZUpTHTrA

Here's a ruby script working
https://gist.github.com/sb8244/3865c630a445f43eca60aaec43d6ecab

I think I'm close but no cigar yet :(

**Comment by Spomky** [comment]
Hi,

This small example works fine on my platform:

```php
use Base64Url\Base64Url;
use Jose\Component\Core\AlgorithmManager;
use Jose\Component\Core\JWK;
use Jose\Component\Core\Converter\StandardConverter;
use Jose\Component\Encryption\Algorithm\KeyEncryption\A256GCMKW;
use Jose\Component\Encryption\Algorithm\ContentEncryption\A256GCM;
use Jose\Component\Encryption\Compression\CompressionMethodManager;
use Jose\Component\Encryption\Compression\Deflate;
use Jose\Component\Encryption\JWEDecrypter;
use Jose\Component\Encryption\Serializer\JWESerializerManager;
use Jose\Component\Encryption\Serializer\CompactSerializer;

$keyEncryptionAlgorithmManager = AlgorithmManager::create([
    new A256GCMKW()
]);

$contentEncryptionAlgorithmManager = AlgorithmManager::create([
    new A256GCM()
]);

$compressionMethodManager = CompressionMethodManager::create([
    new Deflate(),
]);

$jweDecrypter = new JWEDecrypter(
    $keyEncryptionAlgorithmManager,
    $contentEncryptionAlgorithmManager,
    $compressionMethodManager
);

$secret = 'JdbnTFijRYcOJ0rg4CFnl2KnPSHJ1FaJbP6H30rIAB_asozaEDz4iRh4rZFmZDNR';
$key = hash('sha256', $secret, true);

$token = 'eyJhbGciOiJBMjU2R0NNS1ciLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJnaExrcWJwdlZtNW9VanprIiwidGFnIjoiMUpFOEZGdGZlZzNGSGRMeFNXZUx4QSJ9.b4F3UtiJ4Ngkptjlz0oQjXw9UJcD4f5fnKdwSVrisk8.r0GC8Wo9Oy_8BUCI.RUV0gKLlH7hiFIjr8K6c2gc00lxzqW_blxVDgRUUh_Ve_T8Ff7WGMfgrb8mLX2QEOupCOaPo-xzrYmwjtWmPxUf3WGaRDtKc5yGslKfpI8xv0p2T5IfIG2vaBqCGmNthM955DpCjFEtSlzHV3yw6qbYO3nWM646TeE0rCgYjIkJtFH4z8brDTxdhuhps0RvmWfjVWBQWdaHYL6vfciJcfrUc9iUGJNY16qA14PuNBOR32i2iG7N_W_z0HlDcJQUatyn--plnDJ3Kle9IpURVsReZc1Tn-DM-MpeGyCufHoIZ6QKgtLx4tpBAhD7_k9HIl9Ltx6bGp_UHyZLspYDLIW5VESLRjoA9_Lz5NnFegoDRVqWzdjOI0ZhKj2NmP_cu3SFUe7cNkGhOZV9Al_NgwPE-5IItQt69QZcTD1TfF8aAafOL7VMqDpjEFG3UzVAs9u4KW18-HlCUfEl5pXEnkAQf3hy8s1eFGF3JV6ilFnHzrqvrJd8FBp3TE_6536OBI8FkwKPiwqbOVcPZajBHloctRoYNMU9YR-6VoCoh3krM7J01JM5bGD0imL8SvUpqM6KrN1_lW7_1xmT4muvwduNYJk9mkDwtRJXZrz6pa5H1G3f3BJMWmB5pi8A3LHNxg8EgqVdZIdaI0BnXgaHFk3ZcBMGLXjhS1JBnTbjJSFLZLT7b0jeqM6gd2ocdZ4JGs57TzzA4CFR8ccKohLGuFgJvBqYcqR3k81GfqNgFJ-EkrqftvjMM5nVX1XIT2qYkwyqWxdglXUURGd5Xa-VhJ8n1b4T8FXfusWk-LYCPIwVyk9FUNyas3vLwplXpqjWdeiUQuSUQUNi4hsGZhsQuqMAPGf23YeAhDahNFh3WSNepkeU28DCW8eBxTRxKdNsOX8FihWp5kkQal9w32qpn7mcTFjpRW3PxvgnOGBW3dw1gd0DoUvpQRurhXxqyA6XtU3OuiDwjbP4Z7n-VJnihYspRd3-yvLXjcA16ERaSseGymETujv7MeRORikbJRx2dlom_79K34qc16HhX8H0LUFPA4fttijTzI9ulQVjSEo3aMd4DHpSGWw5IxylXhV_uMsaCyCYnFN9XkSEzdxpB4AkI6fCbGzmMmsxPoaOwVlglJeEbFsH9e2r4Q83DymLpS2tk3uA3IEZNLxmygUem78eqjGh34g8j4VgpPiIk8GG-HWRHdtoyEKJAUTHztS8qvm7Fsv_bPV16gu8fGoQ1YwS1SenvYTk9KBGqVX5QMSNnyPU5LNHYCOPB1LC4GJBamZrhVzZxzLidX0NMqhYvNOvjrZhneyDnj4Kur1g0T9Qqj8zD27KLcCdnVXKgw3VXRgJj5KqhcraXy6V43Lx6yotWExUVLGtTCK6BjuW9i91Bx3N7APCWAlxX65hjj3gt3Z1TVW7kjs2mLh-yjGUzyUDCXns2mfu4XlRTJHahc4f2q4NYiovddrB4T0NW8oieunSQwwvnh7I6DURWP0wmVsobp1cb8XfZKFLCRyVoI6xtdXqB8tv0DSA5B8FNwSJt-7xsfrB2UHQMzKQyAN_MSSpuN-xqwzhYhmhP7kvkoTRt4z2st4tjwwW4nt8K2zTbU7t5kdC3bIf3m5twUEQda8FEuIpmdXA1_MTLQorFhAjZqXotCwbNAM9N0-N7lEZmJK5LeovsxmONp9PIrA_1uZ-4m8NO3Ij32hXzvas_dzTHeqLzvtx882AhsTXardAIwyEnKFUYRCMWW6WQV-vEdbJI2VdyHSStoqt6lQ.N-Ji_j2_8hUh4tZUpTHTrA';

$jwk = JWK::create([
    'kty' => 'oct',
    'k' => Base64Url::encode($key),
]);

$jsonConverter = new StandardConverter();

$serializerManager = JWESerializerManager::create([
    new CompactSerializer($jsonConverter),
]);

$jwe = $serializerManager->unserialize($token);

$jweDecrypter->decryptUsingKey($jwe, $jwk, 0);
dump($jwe->getPayload());
```

Have fun :+1:

**Comment by mwleinad** [comment]
OMG is working!! 
I never'd get this correctly
so basically the unwrapKey method is
$kek = Base64Url::decode($key->get('k'));
so that's why I needed to encode it first?

Thanks! It was driving me crazy!

**Comment by Spomky** [comment]
Excellent!
Now closing as resolved.
Feel free to open it again if needed.
