### ISSUE TITLE
Question: Missing iss checker?

### ISSUE THREAD

**Issue by haroldmodesto** [web-token/jwt-framework#144]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.2.3

I'm new to this framework and to JWT in general. I was looking for an issuer checker under Component/Checker and did not find any.  I was about to write one when I found IssuerChecker class as one of the stubs under tests. I may be missing something fundamental to the library - why doesn't the framework "officially" include an "iss" claims checker?

**Comment by haroldmodesto** [comment]
@Spomky Thanks that clears it up and thank you for all your work on this framework.

**Comment by Spomky** [comment]
Closing as integrated in the v2.0 to be released by the end of the month.
