### ISSUE TITLE
Split off  Symphony bundling

### ISSUE THREAD

**Issue by DASPRiD** [web-token/jwt-framework#153]
Right now, this package introduces a lot of dependencies which are only useful when you actually use the symphony bundle. I'd recommend to split that bundle of into a separate package to keep this one lightweight.

**Comment by DASPRiD** [comment]
Actually nevermind, I misunderstood the project structure with the other packages :)

**Comment by Spomky** [comment]
No worries. You will find the list of packages in the [`replace` section of composer.json file](https://github.com/web-token/jwt-framework/blob/v1.2/composer.json#L85-L107).
Just pick the ones you need.
