### ISSUE TITLE
Do we need JsonConverter?

### ISSUE THREAD

**Issue by mdeboer** [web-token/jwt-framework#158]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.3.0 / 2.0.0

Just wondering why there is a `JsonConverter` interface with a `StandardConverter` implementation. I understand that some extra options like `JSON_UNESCAPED_SLASHES` and `JSON_UNESCAPED_UNICODE` are used in `StandardConverter` but I don't see why anyone would write a custom converter, what other ways are there to convert to JSON?

Take for example the `JWSBuilder` which has a `withPayload` method but it only accepts a string. Why not alter this method to accept both strings and arrays. In case of an array, use `json_encode` with the required options (mentioned above). This would cause no BC issues as a string is still accepted. You could deprecate the `JsonConverter` with a new v1 release and remove it in v2.

I'm happy to discuss and implement this change if you like.

**Comment by Spomky** [comment]
Hi,

This interface is used to convert the payload, but also the headers and to serialize into the non-compact serialization modes.

But you are right when you write that nobody will implement its own converter and I agree with you: it can be marked as deprecated and removed in v2.

Regarding the payload, I prefer to keep the current method signature: the setter waits for a string, the getter returns a string.
I tried to handle several input types in the spomky-labs/jose library and it was a terrible mess. From type of payloud is application specific and the library should not care if you want to transmit a message, a key set, claims or an other object.
The application knows how to convert that payload based on the context (or the `cty` header parameter if set).

**Comment by mdeboer** [comment]
Looks good, you're right about the payload. Anything can be stored really and a string makes sense.

Thanks again, closing this 😁
