### ISSUE TITLE
Creating an OKP with JWKFactory creates too long a private key for signing

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-token/jwt-framework#165]
**Describe the bug**
When using `JWKFactory::createOKPKey(Ed25519)` a 64 byte secret key is created. When used to [sign a token](https://github.com/web-token/jwt-framework/blob/8da90ccbead117ace5fb6ef15e5a85440e9295d5/src/SignatureAlgorithm/EdDSA/EdDSA.php#L33), a SodiumException is thrown:
```
seed should be SODIUM_CRYPTO_SIGN_SEEDBYTES bytes
```
Note that the constant is defined as 32. Your tests for OKP creation and signing use a manually created 32 byte private key `d`.

PHP Version: 7.3.2

**To Reproduce**
```
$key = JWKFactory::createOKPKey('Ed25519');
$algorithmManager = AlgorithmManager::create([new EdDSA()]);
$jwsBuilder = new JWSBuilder(new StandardConverter(), $algorithmManager);

$jwtSigned = $jwsBuilder
            ->create()
            ->withPayload('')
            ->addSignature(
                $key,
                [
                    'crit' => ['exp', 'aud'],
                    'alg'  => ''EdDSA',
                ]
            )
            ->build();
```

**Expected behavior**
The token to be signed.

**Comment by moderndeveloperllc** [comment]
Is it correct that in `createOKPKey` you are creating the key pair:
```
case 'Ed25519':
                $keyPair = \sodium_crypto_sign_keypair();
                $d = \sodium_crypto_sign_secretkey($keyPair);
                $x = \sodium_crypto_sign_publickey($keyPair);
```

And then _recreating_ that secret key:
```
        $secret = Base64Url::decode($key->get('d'));
        $keyPair = \sodium_crypto_sign_seed_keypair($secret);
        $secretKey = \sodium_crypto_sign_secretkey($keyPair);
```
Isn't `d` already the secret key? Can it not just be 
```
$secretKey = Base64Url::decode($key->get('d'));
```

In `verify` right below that you are doing `$public = Base64Url::decode($key->get('x'));`

**Comment by Spomky** [comment]
See #168 and `v1.3.2`
