### ISSUE TITLE
[Symfony] How to prevent jku request when testing?

### ISSUE THREAD

**Issue by marijnhurkens** [web-token/jwt-framework#169]
For my tests I have created a test jwk set and I put this in a test override config file:

packages/test/jose.yaml:
```
jose:
    key_sets:
        openid_key_test:
            jwkset: 
                value: 'my test jwk set'
```

Now I also override my authentication service configuration with the test keyset instead of the normal JKU keyset.

services_test.yaml
```
    test.App\Service\MyAuthService:
        class: App\Service\MyAuthService
        arguments:
            - '@jose.key_set.openid_key_test'

```

The problem is that, even though the JKU keyset is never used when testing it still tries to request it. Now I would rather prevent this as this makes my tests dependent on this external endpoint which I don't want to use.

Why does this happen? Does Symfony resolve all the keysets (which triggers the HttPlug request) even though they aren't used? How can I prevent this?

I tried overriding the normal keyset with a new config, but then jwt-framework will error on the keyset having both a jku url and a jwk keyset.

**Comment by Spomky** [comment]
What you can do is to use the [Httplug Mock Client](http://docs.php-http.org/en/latest/clients/mock-client.html).
THis client is used in the tests of the bundle. Have a look at [the configuration file](https://github.com/web-token/jwt-framework/blob/v1.3/src/Bundle/JoseFramework/Tests/config/config_test.yml). You'll see that fake uris like `https://foo.bar/keys.jku` are set but when called the mock client returns a [pre-formatted http response](https://github.com/web-token/jwt-framework/blob/v1.3/src/Bundle/JoseFramework/Tests/Functional/KeyManagement/JWKSetLoaderTest.php#L108)

**Comment by marijnhurkens** [comment]
Thanks, that solution works perfect :)
