### ISSUE TITLE
Need PHP7.0 support for spomky jwt-framework

### ISSUE THREAD

**Issue by urmamb** [web-token/jwt-framework#170]
Hi,

I would love to use jwt-framework library but PHP versioning stops me.

Our server is on debian 9 stretch which is the latest stable release until now. I want to use those packages which are officially released by debian. In this case PHP7.0 is the official release for debian stretch.

PHP7.3 will be there in debian bluster but bluster is yet in test. 

[Composer](https://packagist.org/packages/web-token/jwt-framework) require > PHP7.1
I would love to use this library but don't know how is it possible in a debian stable environment.

**Comment by mdeboer** [comment]
Just install PHP 7.2 or 7.1, you gotta keep up with the PHP versions somehow. You can't tell *all* dependencies to drop to 7.0.

Anyway here's some reading material: https://www.rosehosting.com/blog/how-to-install-php-7-2-on-debian-9/

They use the Sury repository to install the latest PHP versions. Seems like a credible guy that's been at it for a long time (in case you're worried): https://deb.sury.org/

**Comment by urmamb** [comment]
@mdeboer Thank you. I know about what you suggested but i want to stick to the stable and official product.

**Comment by moderndeveloperllc** [comment]
@urmamb Just a point about what @mdeboer said. @oerdnj is actually the [maintainer for the PHP package](https://packages.debian.org/source/stretch/php-defaults) for Debian (amongst other packages). Using his package at https://packages.sury.org/php/ is basically using the stable, official package :-)

On a coding level @Spomky is using nullable types on his method declarations (>= PHP 7.1), That means a substantial degrading or removal of return typing to fo back to 7.0.

**Comment by urmamb** [comment]
@moderndeveloperllc Thank you. We already had used sury's package on our environment and there comes a point where we had to face a lot of issues and we had to rollback to 7.0.

Lets wait for the debian bluster then.

**Comment by Spomky** [comment]
Hi,

I am sorry @urmamb, but @moderndeveloperllc is right, the current source code uses features introduced in PHP 7.1. Moreover PHP 7.0 is not supported anymore, even for security fixes.

I understand you have troubles with the new versions of PHP, but that’s not a reason for adding code regressions here.

**Comment by Spomky** [comment]
Closing as answered.
