### ISSUE TITLE
Stop jwt-key-mgmt from tanking performance by setting required PHP version to >=7.2 or removing polyfill

### ISSUE THREAD

**Issue by aleskr** [web-token/jwt-framework#171]
So I was being stupid today and added a popular dependency without checking all it's dependencies. I pushed it to prod after testing and the servers tanked as a result of web-token/jwt-key-mgmt being insanely slow, even when not being used.

**So what went wrong?**
web-token/jwt-key-mgmt depends upon a polyfill for ext/sodium (paragonie/sodium_compat), and this results in paragonie/sodium_compat code being executed on every single request when the composer autoloader is used, thereby tanking the server performance. Performance dropped to ~65 %(17k to 11k rps).

**Possible solutions**
Removing the polyfill would be a good idea as it's only needed by those with an old PHP version. PHP 7.1 is no longer actively maintained and a polyfill can easily be added by those who need it, instead of forcing it on everyone. And I don't think it's as easy to stop a dependency from being installed(?).

Upping the minimum PHP version to 7.2 or removing the paragonie/sodium_compat dependency would solve this issue and remove the risk of ruining performance.

**Comment by Spomky** [comment]
Hi @aleskr,

You are absolutely right and this will be done in the v2.0 branch for which PHP 7.2 will be the minimum requirement (no release date at the moment).
What you can do in your composer.json file is to set an `replace` key with ``:

Ex:

```json
{
    ..._Usual_stuff_here
    "replace": {
        "paragonie/sodium_compat": "*"
    }
}
```

**Comment by aleskr** [comment]
Thanks, that's great to hear, @Spomky :)

**Comment by Spomky** [comment]
Closing now. You can test with the v2.0 branch to verify it is faster or not.
If you use the ECDH-ES key encryption algoirthm on PHP 7.3, this will be really faster (at least 50x)
