### ISSUE TITLE
Cannot generate RSA key with console tools

### ISSUE THREAD

**Issue by shadowhand** [web-token/jwt-framework#182]
**Describe the bug**
Console tools `key:generate:rsa` are broken because they expect a string to be an int:

https://github.com/web-token/jwt-framework/blob/95e1a3bffd2082aa5f9d2976bf384c0fb5c5dc6f/src/Component/Console/RsaKeyGeneratorCommand.php#L36-L40

These lines are an impossible situation, as input values in command line are always strings. The correct check might be:

```php
if (!is_int($size) && !ctype_digit($size)) {
    // throw exception
}
```

**To Reproduce**

```
./jose.phar key:generate:rsa 2048

In RsaKeyGeneratorCommand.php line 39:

  Invalid size

key:generate:rsa [-u|--use [USE]] [-a|--alg [ALG]] [--random_id] [--] <size>
```

**Expected behavior**

A RSA key is generated.

**Comment by Spomky** [comment]
Thank you for reporting this issue.
It is now fixed in v2.0.7.
Feel free to re-open if the issue still exists.
