### ISSUE TITLE
Make "ext-gmp" an optional dependency when not necessary

### ISSUE THREAD

**Issue by thomasvargiu** [web-token/jwt-framework#185]
`ext-gmp` is only used for few and not standard features, and in some packages is required even if not necessary.
For example, `jwt-key-mgmt` requires the `gmp` extension, but it's only used for some key analyzers.

It would be better to:

- remove `ext-gmp` as a hard dependency when not necessary, introducing some check like:
    ```php
  public function analyze(JWK $jwk, MessageBag $bag): void
  {
      if (! \extension_loaded('gmp')) {
          throw new \LogicException(static::class . ' requires gmp extension');
      }
    // ...
  }
    ```
  - `jwt-core`
  - `jwt-key-mgmt`
- add `ext-gmp` as a hard dependecy when necessary:
  - `jwt-encryption-algorithm-ecdh-es`
  - `jwt-util-ecc`

**Comment by Spomky** [comment]
I fully agree with this.
Let me few days to find a way to achieve that. If no BC break then this could be added for the next minor relase v2.1.

**Comment by Spomky** [comment]
Done in v2.0.9.
Let me know if it is not convenient for you or if I missed something.
