### ISSUE TITLE
Jose\Component\Signature\Util\RSA does not exists in v2

### ISSUE THREAD

**Issue by ls-renaud-tilte** [web-token/jwt-framework#190]
**Describe the bug**
When you use composer to install the library (or components of it), v2 comes by default, which is great.

I'm trying to verify a JWT with a JWK by following the example on this page: https://web-token.spomky-labs.com/components/signed-tokens-jws/jws-loading.

My JWK corresponds to a RS256 key, but the verification always fail in

```php
abstract class RSA implements SignatureAlgorithm
{
    public function verify(JWK $key, string $input, string $signature): bool
    {
        $this->checkKey($key);
        $pub = RSAKey::createFromJWK($key->toPublic());

        return JoseRSA::verify($pub, $input, $signature, $this->getAlgorithm(), $this->getSignatureMethod());
    }
}
```

The `JoseRSA` class is an alias for `Jose\Component\Signature\Util\RSA` which does not exists in 2.0.8, and seems to be removed since v2.0.0. However, `master` seems to have the class.

Exception thrown: Class 'Jose\Component\Signature\Util\RSA' not found in `JWSVerifier`
```php
private function verifySignature(JWS $jws, JWKSet $jwkset, Signature $signature, ?string $detachedPayload = null, JWK &$successJwk = null): bool
{
	$input = $this->getInputToVerify($jws, $signature, $detachedPayload);
	foreach ($jwkset->all() as $jwk) {
		$algorithm = $this->getAlgorithm($signature);

		try {
			KeyChecker::checkKeyUsage($jwk, 'verification');
			KeyChecker::checkKeyAlgorithm($jwk, $algorithm->name());
			if (true === $algorithm->verify($jwk, $input, $signature->getSignature())) {
				$successJwk = $jwk;

				return true;
			}
		} catch (Throwable $e) {
			//We do nothing, we continue with other keys
			continue;
		}
	}

	return false;
}
```

**To Reproduce**
Try to verify an RS256 token using example in https://web-token.spomky-labs.com/components/signed-tokens-jws/jws-loading using v2.X of the library.

**Expected behavior**
A valid token should pass validation

**Comment by ls-renaud-tilte** [comment]
Looks like commit https://github.com/web-token/jwt-signature/commit/74eac73c3b605cb84da2b169bd67800611989efc is in fault, it does not make sense to delete this file regarding to the commit message.

Or maybe I'm missing something.

**Comment by Spomky** [comment]
Hi, thank you for this report.
The [class `Jose\Component\Signature\Util\RSA` exists in v2.0.8](https://github.com/web-token/jwt-framework/blob/v2.0.8/src/SignatureAlgorithm/RSA/Util/RSA.php).
It has been removed from the `web-token/jwt-signature` because it is now part of the `web-token/jwt-signature-algorithm-rsa` one.
It is [mentioned in the doc](https://web-token.spomky-labs.com/components/signed-tokens-jws/signature-algorithms) the algorithms have their own package in v2.x

Can you verify the RSA package is correctly installed?

```sh
composer list |grep web-token
```

**Comment by ls-renaud-tilte** [comment]
Output of `composer show -i | grep web-token`

```
web-token/jwt-core                     v2.0.8     Core component of the JWT Framework.
web-token/jwt-key-mgmt                 v2.0.3     Key Management component of the JWT Framework.
web-token/jwt-signature                v2.0.6     Signature component of the JWT Framework.
web-token/jwt-signature-algorithm-hmac v2.0.8     HMAC Based Signature Algorithms the JWT Framework.
web-token/jwt-signature-algorithm-rsa  v2.0.3     RSA Based Signature Algorithms the JWT Framework.
```

1. In `vendor/web-token/jwt-signature-algorithm-rsa/RSA.php`, the `verify()` function depends on `Jose\Component\Signature\Util\RSA`.
2. Autoloader makes it so this namespace points to the signature component
3. If you remove the file from the component, the class cannot be loaded
4. Exception is caught in `JWSVerifier`
5. Because of the `continue`, code fails silently

I managed to get the code working by specifying the commit hash for `web-token/jwt-signature` and force it to `bd15168` (second to last).

**Comment by ls-renaud-tilte** [comment]
Ho I see, I should update the `jwt-signature-algorithm-rsa` to 2.0.8.

**Comment by Spomky** [comment]
Happy to read that it is fixed.
That’s strange to see the RSA package at v2.0.3 when other ones are at v2.0.8.
If not done, your dep versions should be `^2.0` to allow all v2.x versions.
