### ISSUE TITLE
Query regarding Security Patch for using spomky-Labs/jose

### ISSUE THREAD

**Issue by girishassudanizeon** [web-token/jwt-framework#195]
Hello,

This issue is not directly related to this repository.

But i was going through the Spomky-Labs/jose repo and its say that web-token/jwt-framework is highly recommended to use but i noticed it also says there will be security patch from 2019 to 2020.

I am just looking for the security patch if its there is which i can use for couple of months as i have one old project which will end in 2019 and we have already used web-token/jwt-framework in the new version of same project which is under development.

Any thoughts appreciated.

Thank you!

**Comment by Spomky** [comment]
Hello,

There is no patch to apply. The last version on Github is the right version to use.
No security notice have been received so far.
As far as I know there is no risk to use that library.

**Comment by girishassudanizeon** [comment]
Thank you for your response.

I think i got confused going through the readme file for : https://github.com/Spomky-Labs/jose saying below

--------------------------------------------------------------------------------------------------
We highly recommend you to use the new JWT Framework project instead of this library.

    Active support of this library is provided until end of 2018.
    **_Security support will be provided from 2019 and up to end of 2020_**.

A migration guide will be/is available in the documentation of the new project.
--------------------------------------------------------------------------------------------------

Reading the above line saying security support will be provided from 2019 upto end of 2020 brough in my mind that you guys have some fixes or patch to support the existing library.

Thank you!

**Comment by Spomky** [comment]
OK maybe that paragraph is not clear enough.
In any case, if a security issue is found, the last branch will be patched and tagged. A CVE will be addressed so that security tools like https://github.com/sensiolabs/security-checker / https://security.symfony.com/ will warn you.

Closing now. Do not hesitate to re-open if needed.
