### ISSUE TITLE
Migration documentation

### ISSUE THREAD

**Issue by sglessard** [web-token/jwt-framework#197]
Hello,

The migration pages (from `spomky-labs-jose` to `web-token/jwt-framework`) give a 404 : 

https://web-token.spomky-labs.com/migration/spomky-labs-jose
https://web-token.spomky-labs.com/migration/from-spomky-labs-jose

Thanks,

**Comment by Spomky** [comment]
Hi @sglessard,

Where did you got these links? If you go to the [migration page of the v1.x](https://web-token.spomky-labs.com/v/v1.x/migration), the link is correct (https://web-token.spomky-labs.com/v/v1.x/migration/from-spomky-labs-jose).
This page does not exist anymore [in the v2.x branch](https://web-token.spomky-labs.com/migration).

**Comment by stof** [comment]
well, he probably got the link at the time 1.x was the main branch in the doc, as the doc website does not include the branch in the URL for the main one (and so changing the main branch is changing all URLs)

**Comment by Spomky** [comment]
That's correct. The links of the main version does not include the version. The issue will certainly occurs when mew major versions will be released.

I will ask gitbook to change that behavior or create an option.

**Comment by sglessard** [comment]
Simply by browsing https://github.com/Spomky-Labs/jose :

> A migration guide will be/is available in the [documentation of the new project](https://web-token.spomky-labs.com/migration/from-spomky-labs-jose).

**Comment by Spomky** [comment]
Thank you. This is now fixed.

**Comment by Spomky** [comment]
Closing as fixed
