### ISSUE TITLE
Make ext-sodium an optional dependency

### ISSUE THREAD

**Issue by gabema** [web-token/jwt-framework#198]
I'm working on building a FIPS compliant PHP solution and in order to do so have to prove that only openssl based crypto algorithms are in use. Does jwt-framework rely on ext-sodium or is it only an optional dependency that can be configured to be used instead of ext-openssl?

**Comment by Spomky** [comment]
Hi @gabema,

The `ext-libsodium` is required in the framework, but not is sub packages.
It is only required for
* EdDSA signature algorithm (over Ed25519 curve)
* ECDH-ES key encryption algorithms using X25519 curve
* The JWK factory when creating OKP keys (i.e. Ed25519 or X25519 curve based keys).

**Comment by gabema** [comment]
@Spomky Thank you for providing these details. Would you be open to a pull request to add this type of info to the Readme so its clear why the framework dependencies are included? This would be extremely helpful when dev/architects want to include this library but need to articulate dependency usage with compliance/security officers before incorporating 3rd party software.

**Comment by Spomky** [comment]
Agreed. Just let me a few moment to prepare and release the changes

**Comment by Spomky** [comment]
Done in #199 and https://github.com/web-token/jwt-doc/commit/5c8e7913542dc0ff51f68c3497743a2a14b4353f
