### ISSUE TITLE
version 2 removed some factory methods that were not marked as deprecated.

### ISSUE THREAD

**Issue by stof** [web-token/jwt-framework#200]
**Describe the bug**
`\Jose\Component\Checker\HeaderCheckerManager::create`, `\Jose\Component\Core\AlgorithmManager::create`, `\Jose\Component\Checker\HeaderCheckerManager::create` and `\Jose\Component\Signature\Serializer\JWSSerializerManager::create` are gone in 2.x, but they are not marked as deprecated in 1.3.8 and are not listed in the migration guide.

**Expected behavior**
These methods should be marked as deprecated in a 1.3.x release, and the migration guide should list them.

**Comment by stof** [comment]
and the constructors should also become public in a 1.3.x release (otherwise the deprecation cannot be solved)

**Comment by Spomky** [comment]
Hi @stof,

The documentation is now up to date.
Waiting for the end of the tests to merge #201 and tag.

Thank you for this report, I really appreciate.
I close it for now. If you have any comment please continue in #201.
