### ISSUE TITLE
RS* algorithms fail in version 2 with openssl 1.0.2 while it worked in 1.3.8

### ISSUE THREAD

**Issue by stof** [web-token/jwt-framework#203]
**Describe the bug**
When using openssl 1.0.2g (the version available on Heroku when using the heroku-16 stack), the RS256 algorithm fail to verify the signature, while the exact same code works in 1.3.x, or when using openssl 1.1.1c (which I do locally, making the debugging quite hard).

But the changelog does not mention a dependency on specific versions of openssl and the code does not check the version or the availability of the extension either.

**Comment by stof** [comment]
Note that I haven't bisected which version of openssl is the minimum one to make things work.

**Comment by Spomky** [comment]
Could you try with `ext-gmp` as required dependency in your composer.json file?

**Comment by Spomky** [comment]
Should be fixed with v2.0.12. I tried to get rid of GMP in v2.0.[9-11] but it looks like I missed something.

**Comment by stof** [comment]
Note that with a recent openssl version, the new code (using `openssl_verify`) works fine. But it seems it fails with older releases of openssl. I don't see any usage of GMP in this code path.

**Comment by HGButtenT** [comment]
I had a similar problem as described here: RS algorithms not beeing loaded on one of our specific servers, on the others it was working. The old version 1.3.8 is working fine on the specific server. 

After a while of debugging I found out that the rsa algorithms are only autowired if the GMP extension is loaded:

[https://github.com/web-token/jwt-framework/blob/v2.1/src/Bundle/JoseFramework/DependencyInjection/Source/Signature/SignatureSource.php](url)
```
if (\extension_loaded('gmp')) {
    $algorithms[RSAPSS::class] = 'signature_rsa.php';
}
```

If I remove the if clause the signatures are loaded and the code works fine for me. Is this a leftover from the GMP removal? Should this be removed on the latest version? Or is GMP still needed in the latest version? 

Framework version: Installing web-token/jwt-framework (v2.1.1)
