### ISSUE TITLE
Can I use this for core php project

### ISSUE THREAD

**Issue by infuginindia** [web-token/jwt-framework#205]
Hi Can I use Core PHP project,
if yes how to call autoload.php and how to make object, if you have any code sample, please send us 
Thank you

**Comment by moderndeveloperllc** [comment]
@infuginindia Yes, this can be used with any PHP framework. @Spomky does include lots of Symfony classes, but they are all optional. 

You will want to check out the documentation. Each of the [components](https://web-token.spomky-labs.com/components) has a [composer](https://getcomposer.org/doc/) `require` statement at the top of the documentation page that is used to include the classes. The documentation also has the `use` statements like:
```
use Jose\Component\Core\AlgorithmManager;
use Jose\Component\Signature\Algorithm\PS256;
use Jose\Component\Signature\Algorithm\ES512;
```
that will include the classes. By "Core PHP", do you mean an existing framework like CakePHP, Zend, Symfony, etc, or do you mean a system you are doing yourself? If the former, most of them already have places where the composer-generated `autoload.php` file is included. If not, at the top of the first processed php file, you would want something like:
```
require_once "vendor/autoload.php";
```
You may need to change the path to where the composer-generated `vendor` folder is relative to your php file. Look for composer tutorials online if you need further help.

**Comment by Spomky** [comment]
Thank you @moderndeveloperllc  for the detailled answer.
Closing as answered.

@infuginindia please note that no commercial support is available here except for active supporters.
