### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Jose\Easy\Load' 

### ISSUE THREAD

**Issue by infuginindia** [web-token/jwt-framework#206]
Fatal error: Uncaught Error: Class 'Jose\Easy\Load' not found in C:\xampp1\htdocs\jwt2\index.php:23 Stack trace: #0 {main} thrown in C:\xampp1\htdocs\jwt2\index.php on line 23

**Comment by infuginindia** [comment]
[index - Copy.zip](https://github.com/web-token/jwt-framework/files/3573778/index.-.Copy.zip)

**Comment by Spomky** [comment]
[`In version 2.1, an "Easy" component will be released.`](https://web-token.spomky-labs.com/easy)

The v2.1 is not yet released and the component not available at the moment.
What you can do is to have a look at [the PR for this component](https://github.com/web-token/jwt-framework/pull/184) and [the associated branch](https://github.com/web-token/jwt-framework/tree/Easy/src/Easy)

**Comment by infuginindia** [comment]
its also giving error 
http://prntscr.com/p1mme9
http://prntscr.com/p1mmvf

**Comment by infuginindia** [comment]
that fixed now this issue coming 
http://prntscr.com/p1mouu
