### ISSUE TITLE
too confusion 

### ISSUE THREAD

**Issue by infuginindia** [web-token/jwt-framework#209]
Hi Is there any way to not to set too many things , like algorithm , checker, etc.
Just give do this  jws-creation

always giving error 
Fatal error: Uncaught Error: Call to undefined method Jose\Component\Core\AlgorithmManager::create() in C:\xampp1\htdocs\jwt2\index.php:34 Stack trace: #0 {main} thrown in C:\xampp1\htdocs\jwt2\index.php on line 34

I need ES256, token to create JWT 
https://web-token.spomky-labs.com/v/master/components/signed-tokens-jws/jws-creation

**Comment by Spomky** [comment]
Hi,

This is a known problem. The learning curve is quite impressive and that’s why the #184 has been created.
Regarding your issue, this method has been deprecated in v1.x and removed in v2.0. You have to use the constructor instead.
Can you tell me from where you copied/pasted this line of code? I may have missed something in the documentation.

**Comment by infuginindia** [comment]
Thanks May you please let me know how can I install Version below 2.0 as I am trying to installed ES256 algo with command -> composer require web-token/jwt-signature-algorithm-ecdsa

its saying nothing to install 


// loading algoridhm
use Jose\Component\Core\AlgorithmManagerFactory;
use Jose\Component\Signature\Algorithm\ES256;
use Jose\Component\Encryption\Algorithm\KeyEncryption\PBES2HS512A256KW;
use Jose\Component\Encryption\Algorithm\ContentEncryption\A128CBCES256;

$algorithm_manager_factory = new AlgorithmManagerFactory();
$algorithm_manager_factory
    ->add('ES256', new ES256())
    ->add('A128CBC-ES256', new A128CBCES256())
    ->add('PBES2-HS512+A256KW', new PBES2HS512A256KW())
    ->add('PBES2-HS512+A256KW with custom configuration', new PBES2HS512A256KW(128, 8192))
;

use Jose\Component\Core\AlgorithmManager;
use Jose\Component\Core\Converter\StandardConverter;
use Jose\Component\Core\JWK;
use Jose\Component\Signature\JWSBuilder;

// The algorithm manager with the ES256 algorithm.
$algorithmManager = AlgorithmManager::create([
    new ES256(),
]);

// Our key.
$jwk = JWK::create([
    'kty' => 'oct',
    'k' => $arr['access_token'],
]);

// The JSON Converter.
$jsonConverter = new StandardConverter();

// We instantiate our JWS Builder.
$jwsBuilder = new JWSBuilder(
    $jsonConverter,
    $algorithmManager
);

// The payload we want to sign. The payload MUST be a string hence we use our JSON Converter.
$payload = $jsonConverter->encode([
    'iat' => time(),
    'nbf' => time(),
    'exp' => time() + 3600,
    'iss' => 'My service',
    'aud' => 'Your application',
]);

$jws = $jwsBuilder
    ->create()                               // We want to create a new JWS
    ->withPayload($payload)                  // We set the payload
    ->addSignature($jwk, ['alg' => 'ES256']) // We add a signature with a simple protected header
    ->build();                               // We build it


    print_r($jws);

**Comment by infuginindia** [comment]
And when you going to release easy way ?

**Comment by Spomky** [comment]
The method `add` returns `null` so chained calls is not available,
You have to refactor that part. By the way there is no need to use the factory.

> And when you going to release easy way ?

End of 2019
