### ISSUE TITLE
1.0 - 2.0.13 migration attempts fail

### ISSUE THREAD

**Issue by srgjames** [web-token/jwt-framework#217]
The below code is constantly giving me Fatal error: Uncaught Error: Call to undefined method Jose\Component\Signature\Serializer\JWSSerializerManager::create() 
I can see the Composer is set correctly the correct files are their. Not sure what im doing wrong. Sadly updating Server with new build and cant get  version 1.3 so my code would still work.
```
use Jose\Component\Core\AlgorithmManager;
use Jose\Component\Signature\Algorithm\RS256;
use Jose\Component\Signature\JWSVerifier;
use Jose\Component\Signature\Serializer\JWSSerializerManager;
use Jose\Component\Signature\Serializer\CompactSerializer;

 $algorithmManager = new AlgorithmManager([
        new RS256(),
     ]);        
     $jwsVerifier = new JWSVerifier($algorithmManager);
     $serializerManager = Jose\Component\Signature\Serializer\JWSSerializerManager::create([ 
          new Serializer\CompactSerializer(),
          new Serializer\JsonFlattenedSerializer(),
          new Serializer\JsonGeneralSerializer(),
      ]);
      
      $jws = $serializerManager->unserialize($access_token);
```

**Comment by Spomky** [comment]
Hi @srgjames,

I am sorry to read that you have troubles during the migration.
Why is it impossible to go to 1.3?
What dependency is blocking the update?

**Comment by srgjames** [comment]
@Spomky 

So Composer only gives the Option to update to 2.0 or higher even using Composer to set specific versions. Going to try some more testing to see how to get the 2.0.13 version working. Any Idea when you are looking to release the 2.1 ?

**Comment by srgjames** [comment]
I ended up Fully removing the Composer install starting fresh and forcing composer.json to have the 1.13 version worked. Did try multiple times with the 2.0.13 and could not get it to work at all.

**Comment by Spomky** [comment]
If you want to migrate without any effort, you first have to update to the last version of the v1.x branch (1.3.9) and fix all deprecation notices you may have.
When done, you can go to v2.0.
This is explained [in the dedicated doc page](https://web-token.spomky-labs.com/migration/from-v1.x-to-v2.0). If you directly go to v2.0, you will undoubtedly face to lot of issues.

**Comment by Spomky** [comment]
Closing as answered.
Feel free to re-opened if needed
