### ISSUE TITLE
Apparently useless requirements in jwt-core.

### ISSUE THREAD

**Issue by hirvinen** [web-token/jwt-framework#218]
**Describe the bug**
Package web-token/jwt-core declares a requirement of beberlei/assert. However, it does not seem to be used by the package, thus resulting in unnecessary package and php extension installation requirements.

**To Reproduce**
1. composer install web-token/jwt-core
2. If your php doesn't have ext-intl enabled, installation will fail.
3. If your php installation does have it, beberlei/assert along with its dependencies will be installed.

**Expected behavior**
No unnecessary dependencies are installed, no unnecessary php extension requirements.

**Desktop (please complete the following information):**
Any.

**Comment by Spomky** [comment]
Hi @hirvinen,

You are right this dependency is now useless and can be removed.
This will be done soon

**Comment by Spomky** [comment]
Fixed in v2.1.0.
