### ISSUE TITLE
Load Ed25519 key

### ISSUE THREAD

**Issue by sv-db** [web-token/jwt-framework#219]
Hi, im trying to implement your framework. I've got it all working upto loading a a Ed25519 key. When i generate a key trough ``` $key = JWKFactory::createOKPKey('Ed25519'); ``` everything works fine, but when I try to load a openssl generated PEM keyfile from disk i'm getting a Invalid argument exception with Unable to load the key.

Is there any way to do this?

**Comment by Spomky** [comment]
Hi @sv-db,

Unfortunately, the conversion from PEM to JWK for Ed25519/X25519 and Ed448/X448 curves is not supported.
As the [RFC8410](https://tools.ietf.org/html/rfc8410) is now a proposed standard, this feature could be added.

**Comment by mirkojoshua** [comment]
Hi
First of all, Thanks for your great work!
I am interested on this feature. In particular the load of PEM file for X25519 key pairs. 
There are any update?

**Comment by mdeboer** [comment]
> Hi First of all, Thanks for your great work! I am interested on this feature. In particular the load of PEM file for X25519 key pairs. There are any update?

https://www.rfc-editor.org/info/rfc8410

This states it is still a proposed standard, not an actual standard yet.

**Comment by Spomky** [comment]
Hi @mdeboer,

Thank you for the reminder.
I created a PR for that (still in progress). I need to add tests to make sure it works fine.

**Comment by Spomky** [comment]
Will be available in 3.1.0
