### ISSUE TITLE
`Easy\Load::jws(..)->run()` not verifying token with public key

### ISSUE THREAD

**Issue by robbash** [web-token/jwt-framework#221]
Hey @Spomky 

I hope it's appropriate to raise this as a bug. Please advise if it's not and let me know how to achieve the verification with the `Easy` approach.

Cheers

**Describe the bug**
In the _Easy_ way, and when `run()` is executed there is verification the JWS with a keyset executed (see [here](https://github.com/web-token/jwt-framework/blob/v2.1/src/Easy/Validate.php#L61)), but the outcome is not used/evaluated. The verification method returns a boolean value indicating if it's valid or not, no exception is thrown, so it has no effect.

**Expected behavior**
There should be an exception thrown if the token cannot be verified.

**To Reproduce**
1. Use the code sample to verify a token [_the easy way_](https://web-token.spomky-labs.com/easy), `Load::jws(..)`
2. Use a public key (string/file) to verify the token

**Additional context**
- web-token/jwt-framework v2.1
- PHP 7.3

**Comment by Spomky** [comment]
Should be fixed in `2.1.1`

**Comment by robbash** [comment]
Excellent, thank you!

**Comment by Spomky** [comment]
Closing as done
