### ISSUE TITLE
jwt-key-mgmt has multiple identical releases

### ISSUE THREAD

**Issue by marc-mabe** [web-token/jwt-framework#222]
**Describe the bug**
The sub repository https://github.com/web-token/jwt-key-mgmt has multiple identical releases pointing to the exact same commit.

We are using dependabot and get automatic PRs on dependency updates but very often there is nothing changed.

**To Reproduce**
Check the releases of https://github.com/web-token/jwt-key-mgmt1

**Expected behavior**
I would expect releases on changes only.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Spomky** [comment]
Hi Marc,

The tags are automatically created when the main branch is updated and the sub-repositories are split, even if there is no change. I understand your concern and normally dependabot is able to [ignore minor versions](https://dependabot.com/blog/ignoring-major-version-bumps/).

**Comment by marc-mabe** [comment]
Hi @Spomky,

Would it be possible to modify the automatic process updating sub-repositories in case of no changes?

About dependabot: I don't won't to simply ignore all minor releases as bugfixes can be important or do you mean that there will be never code changes in minor releases of sub repositories?

**Comment by Spomky** [comment]
> Would it be possible to modify the automatic process updating sub-repositories in case of no changes?

I am not sure it is possible. The tags of the sub-packages are all aligned with the tag of the main repository.

> About dependabot: I don't won't to simply ignore all minor releases as bugfixes can be important or do you mean that there will be never code changes in minor releases of sub repositories?

I agree, this is not a good solution. I created a feature request to explain the problem (see https://github.com/dependabot/feedback/issues/758). Do not hesitate to comment or vote up.

**Comment by marc-mabe** [comment]
I just gave my 👍  to it :)
