### ISSUE TITLE
Load::jws($token)  ->  throw Exception new EdDSA for Validate construct.

### ISSUE THREAD

**Issue by SHATCHGA** [web-token/jwt-framework#223]
Hello, I post first time to GitHub.

Load::jws($token)  ->  throw Exception new Algorithm\EdDSA() for Validate construct.

Exception message is 'The extension "sodium" is not available. Please install it to use this method'.

I don't use Algorithm\EdDSA().
And I don't install extension "sodium".
But as of PHP 7.2.0 this extension is bundled with PHP.

Please check this code.

Best Regards.

**Comment by Spomky** [comment]
Hi @SHATCHGA,

Thank you for reporting this error.
In this case, the verification may be done on the function itself and not on the presence of the extension (to be confirmed, but the method name should be the same).
