### ISSUE TITLE
Payload null

### ISSUE THREAD

**Issue by unrave1ling** [web-token/jwt-framework#224]
I am migrating from spomky-labs/jose to v2.1.1.  For the JWE creation, my payload is always showing NULL even though i added withPayload($payload). This also happens for JWE loading. How can I get the full payload content which I used to when calling $jwe->getPayload() method? Thanks.

**Comment by Spomky** [comment]
The JWE object is immutable and the method `withPayload` does not return the same object.
Therefore, you must re-assign the JWE object

```php
// Not valid
$jwe->withPayload($payload);
$jwe->getPayload(); // Returns null

// Valid
$jwe = $jwe->withPayload($payload);
$jwe->getPayload(); // Returns $payload
```

**Comment by Spomky** [comment]
Closing as answered.
Feel free to open it again if this didn't solved your issue.
