### ISSUE TITLE
Create a jwt-core SerializerManager and SerializerManagerFactory

### ISSUE THREAD

**Issue by devsi** [web-token/jwt-framework#226]
**Is your feature request related to a problem? Please describe.**
When utilizing the factories I find I have to import and create separate variables for jwsSerializerManager and jweSerializerManager (+Factories). This can be kind of annoying and means I have to generate new factories for each serializer and manage them independently.

**Describe the solution you'd like**
In the same way AlgorithmManager (+Factory) is in jwt-core, why not create a single SerializerManager. The Serializers are the same between jwt-signature and jwt-encryption anyway.

**Additional context**
<img width="1014" alt="Screen Shot 2019-11-26 at 7 47 41 PM" src="https://user-images.githubusercontent.com/7467531/69692051-bd3fef00-1085-11ea-8b9f-059f46506202.png">

**Comment by devsi** [comment]
I'd be happy to create a PR that implements this. Although it would mean a 3rd implementation of these managers and factories until you remove support for them in jwt-signature and jwt-encryption.

**Comment by Spomky** [comment]
Hi @devsi,

In general, the factories are not needed cases and with the given example it looks like it is superfluous. Except for the Symfony bundle that provides multiple container services or specific use cases, you don't need any factory.

Just for your information, it is planned to move the factories in the Symfony bundle as they are not really needed and creates confusion. The documentation will be adapted accordingly.

For this issue, I would recommend to directly use the algorithm manager, compression method manager and the serializers.

**Comment by devsi** [comment]
I actually like using the factories. In particular AlgorithmManagerFactory is incredibly useful. My scenario creates a JWS followed by a JWE using the JWS token as the payload for the JWE. By using the factory I can simply preload the necessary algorithms and reference them by name. 

Additionally, when I receive a response from the consumed web service I can use the same instance of the AlgorithmFactory to reverse the above encryptions without having to create new instances.

In retrospect, I guess I could have an accessor for AlgorithmManager instead of the factory, and kill the factory and `->add()` the 5 Algo's that I need here instead. I guess that really just leaves the string accessor as a helpful addition.

<img width="1047" alt="Screen Shot 2019-11-27 at 12 05 35 AM" src="https://user-images.githubusercontent.com/7467531/69705088-aca17000-10a9-11ea-9fae-e9caa8df385d.png">
