### ISSUE TITLE
Symfony 5.0 support

### ISSUE THREAD

**Issue by saimon7** [web-token/jwt-framework#227]
Do you plan to support symfony 5.0?

**Comment by lucasvanlierop** [comment]
Just ran into the same issue, can we help out porting it?

**Comment by Spomky** [comment]
Hi,

Sorry for the late reply.
I’ve just created #230 for porting the framework to sf5.0

**Comment by eman1986** [comment]
what's the ETA on this? still getting upgrade errors

**Comment by Spomky** [comment]
Hi @eman1986,

It is now merged and tagged `v2.1.2`
