### ISSUE TITLE
AlgorithmManager add() is private. Could be public.

### ISSUE THREAD

**Issue by devsi** [web-token/jwt-framework#228]
**Is your feature request related to a problem? Please describe.**
AlgorithmManager, if not using the factory, does not let me add Algorithms after initial instantiation.. `->add()` is private.

**Describe the solution you'd like**
Would be ideal if `add()` was made public to allow for this. Otherwise I am constrained to knowing all the algo's for both requests and responses at the time of manager creation. If I only have one manager to handle it all, then it would be preferable to add the algorithms as I need them.

**Describe alternatives you've considered**
If I knew every algorithm in use before I create the manager, then I can bundle them in to an array and new up the manager with them already there. Otherwise use of the factory is preferred in this case.

**Additional context**
Specifically in https://github.com/web-token/jwt-framework/issues/226#issuecomment-558967735 you mention it's superfluous to use the factories. I think right now the factories solve the immediate issue, but if removed, the

**Comment by devsi** [comment]
This is just my opinion. Absolutely no worries if you think this is an unnecessary feature. In conjunction with removing the factories, I feel it would be useful. :)

**Comment by Spomky** [comment]
Closing as reading in #235.
Will be part of the next major release `v2.2`
