### ISSUE TITLE
JWEBuilder, JWSBuilder, multiple AlgorithmManagers

### ISSUE THREAD

**Issue by devsi** [web-token/jwt-framework#229]
**Is your feature request related to a problem? Please describe.**
I have to clone the AlgorithmManager, or create a new instance with just the one algorithm when new-ing up JWEBuilder and JWSBuilder. Their signature is `JWSBuilder($algorithmManager, $algorithmManager, $compressionManager)`.

**Describe the solution you'd like**
If it is truly a manager, it should only be needed once, instead of having to replicate the class. If the one manager contains both the CEK and the KeyEncryption algorithms then they can be referenced by name when used.

<img width="1420" alt="Screen Shot 2019-11-27 at 10 50 41 AM" src="https://user-images.githubusercontent.com/7467531/69751365-cc658200-1103-11ea-9cca-738f02aa1510.png">

**Comment by devsi** [comment]
Again, apologies for creating issues! I'm just listing frustrations as I hit them while developing with the library.

**Comment by Spomky** [comment]
Hi @devsi,

Sorry for the late answer. Just to be clear with that: don't apology for creating issues! I really appreciate that. I really need such feedback to improve the framework, especially if it is related to UX/DX.

I concur with you. The use of 2 algorithm managers adds an unnecessary complexity and the constructor should be changed.

**Comment by Spomky** [comment]
Done in 3.3.x
