### ISSUE TITLE
Output caught exceptions in JWSVerifier

### ISSUE THREAD

**Issue by koenig-dominik** [web-token/jwt-framework#231]
Currently exceptions caught in the following part:
https://github.com/web-token/jwt-framework/blob/08bbefe1efd90281f9f3825dd7b94ab8f3269d4f/src/Component/Signature/JWSVerifier.php#L100-L107
are just thrown away and we have no way to know what was wrong.
In my specific case I tried to find out why my code didn't validate on the server but was working just fine on my local installation, it turned out, that I didn't install the GMP php extension.
There are also many more ways, that this function can result in an exception.

Please add a way to retrieve the exceptions that are just caught here.

**Comment by Spomky** [comment]
Hi @koenig-dominik,

Thank you for reporting me this issue.
Can you tell me how you instantiated the algorithms?
You should see that the GMP extension is not installed when [the algorithm object is created](https://github.com/web-token/jwt-framework/blob/08bbefe1efd90281f9f3825dd7b94ab8f3269d4f/src/SignatureAlgorithm/RSA/RSA.php#L32-L34).
I may have missed something by the way. Is it possible to share with me an example?

Thank you

**Comment by koenig-dominik** [comment]
Hi @Spomky 

Sure, here is how I did it:

```php

$jwkSetKeydata = 'YOURJWK';
$rawJWS = 'YOURJWS';
$allowedTimeDriftSeconds = 10;
$realm = 'YOURREALM';
$keyIndex = 0;

$jwsVerifier = new JWSVerifier(
   new AlgorithmManager([
      new RS256(),
   ])
);

$claimCheckerManager = new ClaimCheckerManager(
    [
      new IssuedAtChecker($allowedTimeDriftSeconds),
      new ExpirationTimeChecker($allowedTimeDriftSeconds),
      new AudienceChecker($realm),
   ]
);

$headerCheckerManager = new HeaderCheckerManager(
   [
      new AlgorithmChecker(['RS256']),
   ],
   [
      new JWSTokenSupport(),
   ]
);

$serializerManager = new JWSSerializerManager([
   new CompactSerializer(),
]);

$jws = $serializerManager->unserialize($rawJWS);

$headerCheckerManager->check($jws, $keyIndex);

$jwkSet = JWKSet::createFromKeyData($jwkSetKeydata);
$isVerified = $jwsVerifier->verifyWithKeySet($jws, $jwkSet, $keyIndex);
if (!$isVerified) {
   // Why exactly did it fail? No way to retrieve that.
   throw new Exception('Failed to verify JWS Token signature');
}

$claims = json_decode($jws->getPayload(), true);
$claimCheckerManager->check($claims, ['aud', 'exp', 'iat']);

```
Update: added claim checking

**Comment by Spomky** [comment]
Hi @koenig-dominik,

Thank you for the example.
I think I have found the error.
Can you tell me if it occurres with the v2.0 branch?

**Comment by cicnavi** [comment]
Hi,

thank you for your great work. I just wanted to confirm GMP extension issue with another case using web-token/jwt-framework:^2.1.
 
I used the 'Easy way' for JWS example from the docs: https://web-token.spomky-labs.com/the-easy-way/easy#jws-creation-and-verification and was getting 'Invalid signature' error, but the real reason was GMP extension missing.

How about adding the extension as a requirement in composer.json, just like "ext-openssl": "*", etc.?

Greetings from Zagreb, Croatia

**Comment by Spomky** [comment]
Hi @cicnavi and thank you for this message,

Ok it is clear for me know there is something wrong with the error messages.
I will improve that and make for this is correctly spotted by the logger.

For v2.x, the algorithms have their own package. Maybe some of them should also be split as well to avoid this type of error and improve the easy component.
