### ISSUE TITLE
jwt-bundle - v2.1.4 - declaration of JoseCollector::collect incompatible

### ISSUE THREAD

**Issue by Bensemer** [web-token/jwt-framework#239]
The declaration of JoseCollector::collect is incompatible with the declaration of  DataCollectorInterface::collect in Symfony 5.

When I try to require the jwt-bundle on my fresh symfony 5(.0.2) project I get the error message
> Fatal error: Declaration of Jose\Bundle\JoseFramework\DataCollector\JoseCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL): void must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in D:\xxx\vendor\web-token\jwt-bundle\DataCollector\JoseCollector.php on line 21
This error prevents the installation of the bundle.

The JoseCollector should use *Throwable* instead of Exception.

**Comment by Spomky** [comment]
Hi @Bensemer,

This issue has already been fixed by #236 but not yet tagged.
This will be done by the end of the week.
