### ISSUE TITLE
Message: The algorithm "PS256" is not supported.

### ISSUE THREAD

**Issue by hi2rashid** [web-token/jwt-framework#242]
**Describe the bug**
Message: The algorithm "PS256" is not supported.

**To Reproduce**

        use Jose\Component\Core\JWK;
        use Jose\Easy\Build;
        use Jose\Component\KeyManagement\JWKFactory;

            $time = time();
            $jws = Build::jws() // We build a JWS
                ->exp($time + 1800) // The "exp" claim
                ->iat($time) // The "iat" claim
                ->nbf($time) // The "nbf" claim
                ->jti('0123456789', true) // The "jti" claim.
                                          // The second argument indicate this pair shall be duplicated in the header
                ->alg('PS256') // The signature algorithm. A string or an algorithm class.
                ->iss('issuer') // The "iss" claim
                ->aud('audience1') // Add an audience ("aud" claim)
                ->aud('audience2') // Add another audience
                ->sub('subject') // The "sub" claim
                ->claim('https://example.com/isRoot', true)
                ->header('kid', 'ebc')
                ->sign($jwk); // Compute the token with the given JWK

               var_dump($jws);

**Expected behavior**
Print the jws output 

**Screenshots**
![image](https://user-images.githubusercontent.com/10250923/73342508-cae54100-428f-11ea-9763-cf31b9af39dc.png)

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser Chrome 
 - Version 79

Followed the same instruction: https://web-token.spomky-labs.com/the-easy-way/easy

**Comment by hi2rashid** [comment]
Solved it now by installing the Algorithms package.

`composer` require `web-token/jwt-signature-algorithm-rsa`

https://web-token.spomky-labs.com/the-components/signed-tokens-jws/signature-algorithms



Now new Error 

Message: Jose\Component\Signature\Algorithm\PS256 requires gmp extension

**Comment by Spomky** [comment]
Hi,

The GMP extension shall be installed on your platform.
I found [that answer on SO](https://stackoverflow.com/questions/51097508/how-to-install-php-gmp-on-macos-high-sierra) that could help you.

**Comment by hi2rashid** [comment]
I followed this https://mycodde.blogspot.com/2020/01/install-php-gmp-extension-in-mamp-2020.html and i was able to get it installed.

**Comment by Spomky** [comment]
Excellent! I am happy to see that this is now solved.
BR.
