### ISSUE TITLE
Add .gitattributes to v1.3

### ISSUE THREAD

**Issue by reedy** [web-token/jwt-framework#245]
Hello!

Are the v1.x/v1.3 branches still supported/maintained? (I had a look, but couldn't see anything obviously documented to say either way) If so, is it possible to get the .gitattributes from v2.x/v2.1 backported/copied into v1.x/v1.3? Then obviously some point releases tagged to get them out?

I don't mind making a PR if it's wanted/accepted into the branch :)

We're looking at using https://github.com/web-push-libs/web-push-php which still uses the old ^1.0 branches (for now?) (see https://github.com/web-push-libs/web-push-php/blob/0f611f8/composer.json#L26-L27), which results in a lot of extra files being brought in (.github, tests etc)

**Comment by Spomky** [comment]
Hi @reedy,

Thank you for your patience. The v1 branch is not supported anymore, but the modification will be helpful for projects that still use it.
No objection for the integration of the .gitattributes file.

**Comment by reedy** [comment]
Cool, thanks! I'll have a look later today

**Comment by Spomky** [comment]
Tagged `v1.3.10`

**Comment by reedy** [comment]
Thanks!

Rough estimate is it saved ~7500 "lines" (out of just over 18000)

**Comment by Spomky** [comment]
In addition to that, I read an interesting paper from [the PHP CC](https://thephp.cc/news/2020/02/phpunit-a-security-risk) where PHPUnit was accessible on production server and therefore creates a critical security issue.
By removing non-necessary files, .gitattributes also prevent such big issue.

**Comment by reedy** [comment]
Yeah... I shall leave my "thoughts" on that (and the composer) one alone. But yes, positive!
