### ISSUE TITLE
mb_str_split is only available in PHP 7.4

### ISSUE THREAD

**Issue by thomasvargiu** [web-token/jwt-framework#249]
`mb_str_split` function is used in `Jose\Component\Encryption\Algorithm\KeyEncryption\Util\RSACrypt` but this function is only available in PHP 7.4 and the polyfill is only available with `symfony/polyfill-mbstring`, so I think we should include the polyfill in the library.

**Comment by slavino** [comment]
Exactly - I did git the issue while trying to deploy this solution on hosting with PHP 7.3. And I see that this was not the only issue and there are also dependencies to Symfony which makes it subproject of that framework. What a pity.

**Comment by Spomky** [comment]
Hi,

This should be fixed with `v2.1.6`.
Let me know if the issue still exist with this version.

**Comment by Spomky** [comment]
>  I see that this was not the only issue and there are also dependencies to Symfony

@slavino what are the deps you see that could lead to an error during the installation or the use of the components?

The use of `symfony/*` components does not mean it is a sub-project of Symfony.
If you install the whole framework you will have to install the bundle and all these `symfony/*` components.
It is preferable to install only what you need. Components other than the Symfony bundle and the console do not require any other symfony component but the polyfill.

**Comment by slavino** [comment]
Mea culpa, I didn't verify the dependencies of `symfony/polyfill-mbstring` . The release v2.1.6 solved the issue with mb_str_split. 

The last issue is that Windows has difficulties with OpenSSL 
`JWKFactory::createRSAKey(
                     4096, // Size of the key
                     [
                         'alg' => 'RSA-OAEP-256', // This key must only be used with the RSA-OAEP-256 algorithm
                         'use' => 'enc'    // This key is used for encryption/decryption operations only
                     ]);` 

but that's to be resolved by developer himself/herself.

**Comment by Spomky** [comment]
> The last issue is that Windows has difficulties with OpenSSL

What you can do is to create the private key on another env. or with another tool and load it with [JWKFactory::createFromKeyFile](https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-management#from-a-key-file).

**Comment by Spomky** [comment]
Closing as fixed

**Comment by chenj100** [comment]
Hello @Spomky,

Seems like this issue appears in 2.2.2 again, simple code to reproduce
```
<?php

require_once 'vendor/autoload.php';

use Jose;
use Jose\Component\KeyManagement\JWKFactory;

$jwk = JWKFactory::createFromSecret(
    'asd',
    [
        'alg' => 'A256KW',
        'use' => 'enc'
    ]
);

$time = time();

$jwe = Jose\Easy\Build::jwe()
    ->exp($time + 3600)
    ->iat($time)
    ->nbf($time)
    ->jti('0123456789', true)
    ->iss('issuer')
    ->aud('audience1')
    ->aud('audience2')
    ->sub('subject')
    ->alg('A256KW') // The "alg" header parameter corresponds to the key encryption algorithm
    ->enc('A256CBC-HS512')      // The "enc" header parameter corresponds to the content encryption algorithm
    ->zip('DEF')          // We compress the payload (optional. Only recommended for large set of data)
    ->claim('is_root', true) // Custom claims
    ->claim('roles', ['ROLE1' => true, 'ROLE2' => 0.007])
    ->crit(['alg', 'enc']) // We mark some header parameters as critical
    ->encrypt($jwk); // Compute the token with the given JWK (public key)

print_r($jwe);
```

Stack trace

```
$ php test.php
PHP Warning:  The use statement with non-compound name 'Jose' has no effect in /home/jchen/code/self/phpjosetest/test.php on line 5
PHP Fatal error:  Uncaught Error: Call to undefined function mb_str_split() in /home/jchen/code/self/phpjosetest/vendor/thecodingmachine/safe/generated/mbstring.php:518
Stack trace:
#0 /home/jchen/code/self/phpjosetest/vendor/spomky-labs/aes-key-wrap/src/AESKW.php(36): Safe\mb_str_split('\xCC\x7Funb5\xDE\x8FZ\xE7\xF7\xE3U\x7FY...', 8, '8bit')
#1 /home/jchen/code/self/phpjosetest/vendor/web-token/jwt-encryption-algorithm-aeskw/AESKW.php(34): AESKW\A256KW::wrap('asd', '\xCC\x7Funb5\xDE\x8FZ\xE7\xF7\xE3U\x7FY...')
#2 /home/jchen/code/self/phpjosetest/vendor/web-token/jwt-encryption/JWEBuilder.php(395): Jose\Component\Encryption\Algorithm\KeyEncryption\AESKW->wrapKey(Object(Jose\Component\Core\JWK), '\xCC\x7Funb5\xDE\x8FZ\xE7\xF7\xE3U\x7FY...', Array, Array)
#3 /home/jchen/code/self/phpjosetest/vendor/web-token/jwt-encryption/JWEBuilder.php(361): Jose\Component\Encryption\JWEBuilder->getEncryptedKeyFromKeyWrappingAlgorithm(Array, '\xCC\x7Funb5\xDE\x8FZ\xE7\xF7\xE3U\x7FY...', Object(Jose\Component\Encryption\Algorithm\KeyEncryption in /home/jchen/code/self/phpjosetest/vendor/thecodingmachine/safe/generated/mbstring.php on line 518
```

BTW 2.1.9 doesn't have this error.

Thank you!
