### ISSUE TITLE
jwt keyset.

### ISSUE THREAD

**Issue by bogdaniel** [web-token/jwt-framework#252]
Hi there, I'm using the symfony bundle with the console and jose bridge on my app.
I was wondering how can I use the console to generate a key set for SL_JOSE_BRIDGE_SIGNATURE_KEYSET and SL_JOSE_BRIDGE_ENCRYPTION_KEYSET I've been reading the docs for two days so far and I didn't manage getting a working keyset. 
I'm always stuck with this error Invalid key or key set.

**Comment by Spomky** [comment]
Hi,

The recommended way is to use the [PHAR Application](https://web-token.spomky-labs.com/console-command/phar-application).

The available commands are the same as the ones listed in the [Console section](https://web-token.spomky-labs.com/console-command/console).

**Comment by bogdaniel** [comment]
Thanks for the advice I will use the phar application instead.
Also for this
key_encryption_algorithm: 'A256GCMKW' # The key encryption algorithm
What command should I use to generate with  that encryption ?

**Comment by Spomky** [comment]
For the `A256GCMKW`, you will need a shared key i.e. a key of type `oct`.
Hereafter the command to generate such key. It also indicates the usage (`--use`), limits the key for this algorithm (`--alg`) and create a random key ID (`--random_id`).

`./jose.phar key:generate:oct 256 --use enc --alg A256GCMKW --random_id`

**Comment by bogdaniel** [comment]
Thanks I was close with the key type but I didn't know from the documentation about --use enc --alg --random_id ( or maybe I don't know how to use the docs ).
I presume that for an rsa512 key the command that I can use would be
`./jose.phar keyset:generate:rsa 512 --use sig --alg RS512 --random_id`

**Comment by Spomky** [comment]
This is [mentioned in the doc](https://web-token.spomky-labs.com/console-command/console#key-generators), but maybe not so clear. Let me know if you have an way to improve it (PRs are welcome).

The `rsa512` algorithm does not exist. It should be RS256, RS384 or RS512.

For shared secret, the the key size should be at least the hash size i.e. for HS256=256 bytes, HS384=384 bytes...

For RSA key, the key size should be at least 2048 bytes. Please read the [Security Recommendations section](https://web-token.spomky-labs.com/advanced-topics-1/security-recommendations#key-size) carefully.

The correct command line for the RS512 algorithm key creation is `./jose.phar keyset:generate:rsa 2048 --use sig --alg RS512 --random_id`

**Comment by bogdaniel** [comment]
```
# jose.phar key:generate:oct 4096 --use enc --alg A256GCMKW --random_id >> enc.json
#jose.phar keyset:generate:rsa --use sig --alg RS512 3 4096 --random_id >> sig_key.json
```
In the end seems to work like this.
Yes in the docs that i found with 512, 256 and I was thinking that is how it should be used. Once I've started working with normal length 2048 4096 everything worked smooth. 
Maybe this should be changed in the docs

**Comment by Spomky** [comment]
4096 bytes for a shared key is way too much. It will takes too much time to compute the signature and will be counter productive. You should use at least 256 bytes and not more than 512 bytes.
4096 bytes for the RSA key is fine. 

Noted for the documentation. This will be reviewed.

**Comment by ChadSikorra** [comment]
I ran into this same issue using the jose bridge in Symfony. I started messing with the phar app but couldn't seem to get the parameters right. I only happened to stumble across this by searching the repo for other people attempting to generate the keys as well.

It would probably be worth it to have an example set of commands or note on the jose bridge for how to actually generate the key set needed in the config.

**Comment by Spomky** [comment]
Hi @ChadSikorra,

I added examples in the documentation (see https://github.com/Spomky-Labs/lexik-jose-bridge/blob/v3.0/Resources/doc/Configuration.md#creation-of-the-keys).
I hope it will be useful now.
Just ask if you see something wrong or not clear enough.

Regards

**Comment by ChadSikorra** [comment]
@Spomky Thanks! That's exactly what I was looking for. I was able to generate the key set and it all makes much more sense now after reading that. Got it working with my project pretty quick. Thanks again for the quick response, and great work on all these libraries.
