### ISSUE TITLE
The gmp extension is still required when it shouldn't be 

### ISSUE THREAD

**Issue by tommygnr** [web-token/jwt-framework#257]
**Describe the bug**
A [bad merge](https://github.com/web-token/jwt-framework/commit/339c88ab29b7a1476ba1a9a6bb546ebf37e9a248) has resulted in the `composer.json` for `web-token/jwt-signature-algorithm-rsa` containing `ext-gmp` in both `require` and `suggest` when in fact it should just be in `suggest`.

**To Reproduce**
View the offending composer.json file in the tagged 2.1.6 version: https://github.com/web-token/jwt-framework/blob/v2.1/src/SignatureAlgorithm/RSA/composer.json

**Expected behavior**
`ext-gmp` should not appear in the `require` section of composer.json

**Comment by Spomky** [comment]
That's correct.
This will be fixed ASAP

**Comment by Spomky** [comment]
Hi,

This should be fixed with `v2.1.7`.
Let me know if the issue still exist with this version.
