### ISSUE TITLE
Class 'Jose\\Component\\Core\\Converter\\StandardConverter' not found

### ISSUE THREAD

**Issue by faizanktk** [web-token/jwt-framework#267]
Class 'Jose\\Component\\Core\\Converter\\StandardConverter' not found
I got this error. So from where i download this file or directory.
Send link or add to composer
Thanks

**Comment by Spomky** [comment]
This class has been deprecuted in v1 and removed in v2.
https://github.com/web-token/jwt-framework/blob/v1.3/src/Component/Core/Converter/StandardConverter.php#L17
