### ISSUE TITLE
Mandatory claims should not be null.

### ISSUE THREAD

**Issue by VincentLanglet** [web-token/jwt-framework#272]
**Describe the bug**
Hi @Spomky, I recently used the ClaimCheckerManager in my project. If I required a claim `context`, I personally expect that
```
[
    'context' => null,
]
```
is reported as invalid. 

**Additional context**
The check is made https://github.com/web-token/jwt-framework/blob/v2.2/src/Component/Checker/ClaimCheckerManager.php#L82

I think that changing `$claims` by `array_filter($claims)` will fix the issue by removing empty values.

The same could be done for https://github.com/web-token/jwt-framework/blob/v2.2/src/Component/Checker/HeaderCheckerManager.php#L114

**Comment by Spomky** [comment]
You are right, claims with a `null` value shouldn’t be rejected.
I will correct this.

**Comment by Spomky** [comment]
Hi @VincentLanglet,
Actually I revised my mind.

The parameter `$mandatoryClaims` is only used to verify that the claim is present.
It is not designed to check the value of that claim.

The value is verified by a ddicated ClaimChecker object.
So `['context' => null]` could be perfectly valid for some use cases and there is no reason to reject the token

**Comment by VincentLanglet** [comment]
I understand, but I think that most of the time `null` won't be a valid use case.

WDYT about providing the ClaimChecker checking for non-nullable value in this library ?
