### ISSUE TITLE
JWE payload is null

### ISSUE THREAD

**Issue by Olvikolvi** [web-token/jwt-framework#274]
Trying to load JWE using easy-way, but don't figure out why it gives this error? Token should be fine.

$jwt = Load::jwe($token)
->algs(['RSA-OAEP'])
->encs(['A128CBC-HS256'])
->exp()
->iat(1000)
->nbf()
->key($jwk)
->run()
;

PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Jose\Component\Core\Util\JsonConverter::decode() must be of the type string, null given, called in xxx/vendor/web-token/jwt-easy/Decrypt.php on line 113 and defined in xxx/vendor/web-token/jwt-core/Util/JsonConverter.php:40
Stack trace:
#0 xxx/vendor/web-token/jwt-easy/Decrypt.php(113): Jose\Component\Core\Util\JsonConverter::decode(NULL)
#1 test.php(177): Jose\Easy\Decrypt->run()

**Comment by Spomky** [comment]
Hi @Olvikolvi,

I am not sure to clearly understand where the issue comes from.
Hereafter an example you can adapt on your environment (it uses different algs):

```php
<?php

require_once 'vendor/autoload.php';

use Jose\Component\Core\AlgorithmManager;
use Jose\Component\Encryption\Algorithm\KeyEncryption\A256KW;
use Jose\Component\Encryption\Algorithm\ContentEncryption\A256CBCHS512;
use Jose\Component\Encryption\Compression\CompressionMethodManager;
use Jose\Component\Encryption\Compression\Deflate;
use Jose\Component\Encryption\JWEBuilder;

// The key encryption algorithm manager with the A256KW algorithm.
$keyEncryptionAlgorithmManager = new AlgorithmManager([
    new A256KW(),
]);

// The content encryption algorithm manager with the A256CBC-HS256 algorithm.
$contentEncryptionAlgorithmManager = new AlgorithmManager([
    new A256CBCHS512(),
]);

// The compression method manager with the DEF (Deflate) method.
$compressionMethodManager = new CompressionMethodManager([
    new Deflate(),
]);

// We instantiate our JWE Builder.
$jweBuilder = new JWEBuilder(
    $keyEncryptionAlgorithmManager,
    $contentEncryptionAlgorithmManager,
    $compressionMethodManager
);

use Jose\Component\Core\JWK;

// Our key.
$jwk = new JWK([
    'kty' => 'oct',
    'k' => 'dzI6nbW4OcNF-AtfxGAmuyz7IpHRudBI0WgGjZWgaRJt6prBn3DARXgUR8NVwKhfL43QBIU2Un3AvCGCHRgY4TbEqhOi8-i98xxmCggNjde4oaW6wkJ2NgM3Ss9SOX9zS3lcVzdCMdum-RwVJ301kbin4UtGztuzJBeg5oVN00MGxjC2xWwyI0tgXVs-zJs5WlafCuGfX1HrVkIf5bvpE0MQCSjdJpSeVao6-RSTYDajZf7T88a2eVjeW31mMAg-jzAWfUrii61T_bYPJFOXW8kkRWoa1InLRdG6bKB9wQs9-VdXZP60Q4Yuj_WZ-lO7qV9AEFrUkkjpaDgZT86w2g',
]);

// The payload we want to encrypt. It MUST be a string.
$payload = json_encode([
    'iat' => time(),
    'nbf' => time(),
    'exp' => time() + 3600,
    'iss' => 'My service',
    'aud' => 'Your application',
]);

$jwe = $jweBuilder
    ->create()              // We want to create a new JWE
    ->withPayload($payload) // We set the payload
    ->withSharedProtectedHeader([
        'alg' => 'A256KW',        // Key Encryption Algorithm
        'enc' => 'A256CBC-HS512', // Content Encryption Algorithm
        'zip' => 'DEF'            // We enable the compression (irrelevant as the payload is small, just for the example).
    ])
    ->addRecipient($jwk)    // We add a recipient (a shared key or public key).
    ->build();              // We build it

use Jose\Component\Encryption\Serializer\CompactSerializer;
use Jose\Easy\Load;

$serializer = new CompactSerializer(); // The serializer

$token = $serializer->serialize($jwe, 0);

var_dump($token);

$jwt = Load::jwe($token)
    ->algs(['A256KW'])
    ->encs(['A256CBC-HS512'])
    ->exp()
    ->iat(1000)
    ->nbf()
    ->key($jwk)
    ->run()
;

var_dump($jwt);
```

**Comment by Olvikolvi** [comment]
Hi,

I don't say its bug because when I create jwe and token as you explained it works, but when I receive token from 3rd party authentication server (big company with many clients) it gives this php-error "null given" mentioned above directly to error.log (not even Exception). When dumping jwe-object inside Decrypt.php run() it seems to be ok with all ciphertext and headers (sharedProtectedHeader = ["cty"]=>"JWT", ["alg"]=>"RSA-OAEP", ["enc"]=> "A128CBC-HS256"]) etc but in line 113: $jwe->getPayload() returns null and then no doubt it fails.
Maby it is keys, wrong enc or something else, but this error message is not helping me forward. Can you help me to debug reason for this?

**Comment by Spomky** [comment]
Hi,

Excuse me for the misunderstanding.
Can you send me samples and keys to help me to dig into that issue? (in private if it contains sensitive data)

**Comment by Olvikolvi** [comment]
You got mail :)

**Comment by vansari** [comment]
Hi @Spomky ,

is it possible that reason for this ticket can be the question/bug which I have opened yesterday evening?!
https://github.com/web-token/jwt-framework/issues/278#issue-715139006

Kind Regards

**Comment by Spomky** [comment]
Thank you.
Let me some time to understand what's going on.

@vansari: yes it could be linked to that issue. The reason why the RSA key used internally is different from the one from OpenSSL is that some useless information are stripped from it (e.g. additionnal prime numbers). But I don't exclude a but in the way the RSA key is rebuilt.
