### ISSUE TITLE
Allow Throwable in Collector interface

### ISSUE THREAD

**Issue by gisostallenberg** [web-token/jwt-framework#275]
**Describe the bug**
The `JoseCollector::collect`'s signature was changed to be compatible with Symfony 5, but while passing the exception (in case it is a `Throwable`) to the collectors this results in another error 'Argument 4 passed to Jose\Bundle\JoseFramework\DataCollector\AlgorithmCollector::collect() must be an instance of Exception or null, instance of TypeError given'.

I suggest widening the accepted type in the Collector interface and the implementing collectors and create a PR for that. Because this might not be BC I create another PR for you which wraps the `Throwable` in an `Exception` and passed that.

**Comment by gisostallenberg** [comment]
You can choose one of the PR's as a solution.

**Comment by laszlopokoradi** [comment]
I am +1 on this issue. I "solved" the problem similarly to PR#276 Allow to pass a `Throwable`.

**Comment by Spomky** [comment]
Done and available in `v2.2.3`

**Comment by gisostallenberg** [comment]
Thanks!
