### ISSUE TITLE
JWKSet::createFromKeys does not exist

### ISSUE THREAD

**Issue by melanger** [web-token/jwt-framework#290]
**Describe the bug**
The [docs](https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-set-management) mention a method `JWKSet::createFromKeys(array $keys)`, which I cannot find in class [JWKSet](https://github.com/web-token/jwt-framework/blob/v2.2/src/Component/Core/JWKSet.php).

**Expected behavior**
Either the method should exist or the docs should not mention it.

**Comment by jbelien** [comment]
Same for `JWK::create()` ; see https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-management

It's mentioned in ["List of deprecation"](https://web-token.spomky-labs.com/migration-1/migration/from-v1.x-to-v2.0#list-of-deprecations) but it still appears in the documentation.

**Comment by Spomky** [comment]
Hi,

Indeed the documentation is not up to date.
You should use the constructor `new JWK([...]);` instead of this method.

**Comment by jbelien** [comment]
Documentation has been updated ; this can be closed 🎉

**Comment by Spomky** [comment]
Great! Many thanks to you.
