### ISSUE TITLE
Jose\Easy\Validate::run() does not check mandatory claims

### ISSUE THREAD

**Issue by wapacro** [web-token/jwt-framework#291]
**Describe the bug**
When using "The Easy Way" and setting mandatory claims, it has no effect. The same has been reported and fixed for v2.1 in #240 - but the bug was reintroduced in v2.2.

| v2.1                                                                                                               | v2.2                                                                                                               |
|--------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------|
| https://github.com/web-token/jwt-framework/blob/dfebe9beee5ac5ef6ccbebdd1f672e7a80f5c79b/src/Easy/Validate.php#L51 | https://github.com/web-token/jwt-framework/blob/1b8d88da2954ed82388ca526531b11919abcf16d/src/Easy/Validate.php#L52 |

The same applies to Decrypt.php:
https://github.com/web-token/jwt-framework/blob/1b8d88da2954ed82388ca526531b11919abcf16d/src/Easy/Decrypt.php#L116

**Expected behavior**
A `MissingMandatoryClaimException` to be thrown.

**Comment by Spomky** [comment]
Many thanks.
Will be tagged `v2.2.6` soon.
