### ISSUE TITLE
For Jose\Easy\Build, add payload or claims method for bulk setting.

### ISSUE THREAD

**Issue by Miniland1333** [web-token/jwt-framework#305]
**Is your feature request related to a problem? Please describe.**
For Jose\Easy\Build, for each claim you want to add you currently have to call ->claim() individually. This is a bit cumbersome if you already have the payload as an object.

**Describe the solution you'd like**
While I am relatively new to PHP, below is some possibly working code of how a `payload` function could simply loop over the `key=>value` pairs and then have a similar internal functionality to the existing `claim()` method. This payload method will thus function similarly to how I've seen it in other libraries where you can just pass in a whole object payload.

```PHP
    public function payload(object $payload): self
    {
        $clone = clone $this;
        foreach($payload as $key => $value) {
                    $clone->jwt->claims->set($key, $value);
        }
        
        return $clone;
    }
```

**Additional context**
While I would recommend using the name `payload()` for the method, you may instead prefer using `claims()`, `setClaims()`, or even overloading your `claim()` method with an object payload.

**Comment by Spomky** [comment]
Hi,

The [`payload` method](https://github.com/web-token/jwt-framework/blob/v2.2/src/Easy/AbstractBuilder.php#L41-L47) already exists.

**Comment by Miniland1333** [comment]
Thanks for finding that! Do you think it would be a good idea for me to document this method in https://web-token.spomky-labs.com/the-easy-way/easy?

Example:
```php
...
// or you can use the payload method to set the claims using an array
$jws = Build::jws() // We build a JWS
    ->header('prefs', ['field1', 'field7'])
    ->alg('RS512') // The signature algorithm. A string or an algorithm class.
    ->payload([
       "iat" => $time,
       "nbf" => $time,
       "exp" => $time + 3600,
       "jti" => 0123456789,
       "iss" => 'issuer',
       "aud" => ['audience1', 'audience2'],
       "sub" => 'subject',
       "https://example.com/isRoot" => true])
    ->sign($jwk) // Compute the token with the given JWK
;
...
```

**Comment by Spomky** [comment]
I added some words about this feature.
It is in the example. If you think it should be in a dedicated section, just ask.

**Comment by Miniland1333** [comment]
I see the changes in the documentation and having this documented will be great for intermediate users who have the payload in an array or object. Thank you @Spomky for doing this!
