### ISSUE TITLE
Multiple Issuers?

### ISSUE THREAD

**Issue by neuquen** [web-token/jwt-framework#306]
I'm interested in allowing multiple issuers when loading a token with `Load::jws()`.  Is that possible?

Something like the following?

    Load::jws($token)->iss($issuer1)->iss($issuer2)

OR

    Load::jws($otken)->iss([$issuer1, $issuer2])

**Comment by Spomky** [comment]
Hi,

A token usually has only one issuer and the [RFC limits the `iss` claim](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1) to a string or an URI.
What is the use case?
