### ISSUE TITLE
Taking 30minute or so to generate JWS token using PS256 algorithm

### ISSUE THREAD

**Issue by lieusq** [web-token/jwt-framework#308]
**Describe the bug**

Hi, I'm facing an issue as per described in the title.

My application is currently running
 - PHP version - 7.3.27
 - GMP version - 6.2.0

This is the sample script that I took from the example.
```
       $cert = "cert.key";
        $key = JWKFactory::createFromKeyFile(
            $cert, // The filename
            'xxxxx'  // Secret if the key is encrypted
        );

        $algorithmManager = new AlgorithmManager([
            new PS256(),
        ]);

        // // We instantiate our JWS Builder.
        $jwsBuilder = new JWSBuilder($algorithmManager);
        // // The payload we want to sign. The payload MUST be a string hence we use our JSON Converter.
        $payload = json_encode([
            'iat' => time(),
            'nbf' => time(),
            'exp' => time() + 3600,
            'iss' => 'My service',
            'aud' => 'Your application',
        ]);
   
        $jws = $jwsBuilder
            ->create()                               // We want to create a new JWS
            ->withPayload($payload)                  // We set the payload
            ->addSignature($key, ['alg' => 'PS256', 'kid'  => 'xxxxxx',]) // We add a signature with a simple protected header
            ->build(); 
       dd($jws->toString());
```
Below is the error I encountered ,if I did not overwrite the default php maximum execution time. If I do and set it as, it will take at least 30minute or so to generate the JWS token. 

```
local.ERROR: Maximum execution time of 30 seconds exceeded {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Maximum execution time of 30 seconds exceeded at /var/www/vendor/brick/math/src/Internal/Calculator/NativeCalculator.php:344)
```
A feedback on this would be gladly appreciated.

Cheers.

**Comment by Spomky** [comment]
Hi,

I can see that the error is thrown from the NativeCalculator class. 
This means neither GMP or BCMath e tensions are loaded. 

You can check the loaded extensions using `get_loaded_extensions()`.
With the version you mention, I presume you installed she library instead the extension
On Ubuntu, the command is `sudo apt-get install php7.3-gmp`

**Comment by lieusq** [comment]
It is working as per what you advised. Appreciate a lot for the prompt reply. @Spomky  .Have a great day sir 😄

**Comment by gitHusband** [comment]
Mark.

Extend GMP for Docker Alpine 3.14 PHP 7.3

<pre><code>
&& apk add --no-cache --virtual gmp-dev \
&& docker-php-ext-install gmp \
</code></pre?
