### ISSUE TITLE
Argument 1 passed to Jose\Component\Core\Util\JsonConverter::decode() must be of the type string, null given, called in /var/www/html/sghealth/server/vendor/web-token/jwt-easy/Decrypt.php on line 117

### ISSUE THREAD

**Issue by yatendra121** [web-token/jwt-framework#310]
$jwe = 'eyJlcGsiOnsia3R5IjoiRUMiLCJjcnYiOiJQLTI1NiIsIngiOiJHUXVCU2FfalJCMHd6eURoWHRVRUk4UDkxT0piTEJoM1EwUVVsZXI4LW9jIiwieSI6IkgyRktTVmNZb2tiREtaRzFKUWNvaVN4LUpQOUs2WjVOY1dkMHlVcTZYWkkifSwiYWxnIjoiRUNESC1FUytBMTI4S1ciLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiY3R5IjoiSldUIn0.0qZegEkn-SQSVRTUa1piGP0l8f_01yOXl_cGXSyzCRr7uIzs2QfQNSz6x7uO36EzxfAcPmtucMIDZCzk4EdbEE17nASmXcXd.anXgdJTPoQFwmXFdeQ0hdw.E9FYOHvAFlbWw8_JNbJbJkxLx8Vhm3_tZDv2KQ7-X2I.BOb1sdKLr7sUGKiBeDBZ643K40PldrIhg88yzfNHa0s';

$jwt = Load::jwe($jwe) // We want to load and decrypt the token in the variable $token
    ->algs(['ECDH-ES+A128KW']) // The key encryption algorithms allowed to be used
    ->encs(['A256CBC-HS512']) // The content encryption algorithms allowed to be used
    ->key($jwk) // Key used to decrypt the token
    ->run() // Go!

**Comment by Spomky** [comment]
Hi,

It looks like the key cannot be used to decrypt the token.
Could you please send me sample data with the private key to have a better understanding on this issue?

Many thanks.

**Comment by yatendra121** [comment]
$jwe = $serializerManager->unserialize($token);
$success = $jweDecrypter->decryptUsingKey($jwe, $jwk, 0);

Thanks, JWE decryption using Easy Way method has not worked for only this JWE. and I had tested with the above method and 
 we have successfully decrypted the above JWE.
