### ISSUE TITLE
the jwt cannot be used immediately after token creation even i set `->iat(1)` with error `The JWT can not be used yet.`

### ISSUE THREAD

**Issue by vatoer** [web-token/jwt-framework#314]
**Describe the bug**
the jwt cannot be used immediately after token creation even i set  or `->iat(1)` 

i also simulate to put `usleep(200000)` before verify `$token` but the the result is not consistent 

i also tried to set `->iat(false)` 

in 10x trial its about 3-4 failed with error `The JWT can not be used yet.`

**To Reproduce**
1. generate token `$token`
2. verify token
```php
usleep(200000);
$jwt = Load::jws($token) // We want to load and verify the token in the variable $token
                ->algs(['RS256', 'RS512']) // The algorithms allowed to be used
                ->exp() // We check the "exp" claim
                ->iat(1) // We check the "iat" claim. Leeway is 1000ms (1s)
                ->nbf() // We check the "nbf" claim
                //->aud('not-checked') // Allowed audience // ! TODO make it configurable
                //->iss('not-checked') // Allowed issuer //
                //->sub('not-checke') // Allowed subject
                //->jti('no-cheked') // Token ID
                ->key($key) // Key used to verify the signature
                ->run() // Go!
            ;
```
3. See Error message `The JWT can not be used yet.`

**Expected behavior**
no error message 

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by Spomky** [comment]
Hi @vatoer,

Thnak you for reporting this issue.
Unfortunately I cannot reproduce it. I generated a token on the fly and used the same verification code you posted.
See the example herefater.
Can you please send me a token or a detailed example so that I can figure out what is going on?

```php
use Jose\Component\KeyManagement\JWKFactory;
use Jose\Easy\Build;
use Jose\Easy\Load;

$key = JWKFactory::createRSAKey(512);

$token = Build::jws()
    ->sub('subject')
    ->iss('issuer')
    ->aud('foo')
    ->alg('RS256')
    ->exp(time()+3600)
    ->iat(time())
    ->nbf(time())
    ->sign($key)
;

dump($token);

usleep(200000);
$jwt = Load::jws($token) // We want to load and verify the token in the variable $token
    ->algs(['RS256', 'RS512']) // The algorithms allowed to be used
    ->exp() // We check the "exp" claim
    ->iat() // We check the "iat" claim. Leeway is 1000ms (1s)
    ->nbf() // We check the "nbf" claim
    //->aud('not-checked') // Allowed audience // ! TODO make it configurable
    //->iss('not-checked') // Allowed issuer //
    //->sub('not-checke') // Allowed subject
    //->jti('no-cheked') // Token ID
    ->key($key) // Key used to verify the signature
    ->run() // Go!
;

dump($jwt);
```

**Comment by VaseemDeveloper** [comment]
Hi @Spomky 
I am using the code written here - https://github.com/aaronpk/sign-in-with-apple-example/blob/master/client-secret.php
To execute the code i need a library from the following.
require('vendor/autoload.php');

use Jose\Component\Core\AlgorithmManager;
use Jose\Component\KeyManagement\JWKFactory;
use Jose\Component\Signature\Algorithm\ES256;
use Jose\Component\Signature\JWSBuilder;
use Jose\Component\Signature\Serializer\CompactSerializer;

Please let me know how can i get the files for above library.
Should i simply run the composer update or copy the files from your repo - **https://github.com/web-token/jwt-framework** to my directory?
