### ISSUE TITLE
Symfony Bundle version 6 support

### ISSUE THREAD

**Issue by a-menshchikov** [web-token/jwt-framework#322]
Is there any plans to add Symfony 6 support for bundle?

**Comment by a-menshchikov** [comment]
@Spomky is there anything I can do to help you with the Preparation3.0 branch?

**Comment by Spomky** [comment]
Hi @a-menshchikov

Thank you for your help.
Actually, there is nothing to do right now. 3.0 is more or less the 2.x + PHP8.0 + type hining - the deprected methods/classes
I am considering a new CI pipeline that breaks all the tests, but nothing diffucult here.
I just need time to make sure everything is fine.

What you can do is start using the v3.0@dev branch and report here any trouble you may have.

Regards.

**Comment by sakarikl** [comment]
When could we expect symfony 6 support to be usable through composer?

This is last project that prevents us from upgrading to symfony 6 :)

**Comment by sakarikl** [comment]
Could it be just added to 2.x branch?

**Comment by KouloukLeGrand** [comment]
Hi,

Like @sakarikl, I am waiting for the JWT Framework to support Symfony 6 to upgrade my project. I prefer to avoid unstable dependencies.

Looking forward to your reply @Spomky 😇

**Comment by a-menshchikov** [comment]
@Spomky few deprecations for you:

> [info] User Deprecated: Method "Symfony\Component\Console\Command\Command::isEnabled()" might add "bool" as a native return type declaration in the future. Do the same in child class "Jose\Component\Console\GeneratorCommand" now to avoid errors or add an explicit @return annotation to suppress this message.

> [info] User Deprecated: Method "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::getName()" might add "string" as a native return type declaration in the future. Do the same in implementation "Jose\Bundle\JoseFramework\DataCollector\JoseCollector" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by Spomky** [comment]
Hi there,

I wish all the best for this New year.
The Symfony 6 support is ongoing on a dedicated branch (https://github.com/web-token/jwt-framework/tree/v3.0).
There are some issues to fix first before tagging.
This new v3.0 is most likely the same as v2.2 without deprecated stuff and type int almost everywhere. 
The Symfony Serializer support will be deprecated in v2.2 as SF6 normalizer interface return type creates too much modifications. I will restore this feature in a next minor realese.

**Comment by mdeboer** [comment]
@Spomky If you don't mind I'll take some time next week to fix SF serializer support as I really require this. Would be nice to have this at launch.

Edit: nvm already fixed it, PR coming in a bit 👍🏻

**Comment by mdeboer** [comment]
Please see https://github.com/web-token/jwt-framework/pull/328

Also, if there is anything else, please let me know.

**Comment by sakarikl** [comment]
Ended up removing web-token/jwt-console package from our composer. After that there wasn't any symfony dependencies.

**Comment by Spomky** [comment]
This is fixed by the v3.0, but I will backport it to v2 for some packages whenever it is possible.

**Comment by mdeboer** [comment]
Just upgraded and it was seamless! 🎉

**Comment by Spomky** [comment]
I am happy to read that.
It's always frightening to jump from one major version to another 😬

**Comment by Spomky** [comment]
I think we can close this issue now.
