### ISSUE TITLE
symetric key encryption for keys

### ISSUE THREAD

**Issue by mschrading** [web-token/jwt-framework#324]
Hi all.

Trying to encrypt simple strings but laptop started heading my room and doesn't come back. I use to take the public "wrapKey" key for building a JWK object 

`$JWK = new JWK($JWKArray); `//Have a look at the attachment file` then: create JWEBuilder()`

then payload()

and 

`
->withSharedProtectedHeader([
   'alg' =>  'RSA-OAEP-256', // Key Encryption Algorithm 'RSA-OAEP-256'
   'enc' => 'A256GCM',  // Content Encryption Algorithm ('A256GCM')
   'zip' => 'DEF'             // We enable the compression (irrelevant as the payload is small, just for the example).
])
`
everything runs fine till I want to ->build() my token!!!

Maybe somebody got a similar problem!?

Any help will be appriciated

Michael

[privateKey.zip](https://github.com/web-token/jwt-framework/files/7704545/privateKey.zip)

**Comment by peerfromme** [comment]
Hi, I had the same problem. The call to build() never returned. It was a missing bcmath extensions, so the BigInteger calculations took forever. I installed the bcmath extension and everything ran flawlessly.

**Comment by Spomky** [comment]
Hi @mschrading,

Sorry I missed this issue. The RSA-OAEP algorithms are slow because of lack of native methods provided by PHP or extensions.
I think @peerfromme is right and installing BCMath or GMP will solve that issue.

**Comment by mschrading** [comment]
Cool! Thanks a lot.
