### ISSUE TITLE
Leeway is not documented correctly

### ISSUE THREAD

**Issue by chrif** [web-token/jwt-framework#325]
In The Easy way doc, it says to use milliseconds for `iat` leeway, but when I look at the code for `IssuedAtChecker`, it assumes leeway is in seconds.

https://web-token.spomky-labs.com/the-easy-way/easy
![image](https://user-images.githubusercontent.com/1298013/148124792-bb3d9b72-43b7-41e1-b90d-715a6cec009f.png)

![image](https://user-images.githubusercontent.com/1298013/148125205-8467fd88-a4e5-457a-a0c3-af6152ffa8d1.png)

https://github.com/web-token/jwt-framework/blob/v2.2/src/Component/Checker/IssuedAtChecker.php
![image](https://user-images.githubusercontent.com/1298013/148124863-8bcb4632-1939-4441-bc80-ca82befa0866.png)

**Comment by Spomky** [comment]
Hi @chrif,

You are right, this will be fixed.

Regards

**Comment by Spomky** [comment]
Closing as modified in the documentation
