### ISSUE TITLE
i have created token according the documentation when i try to decrypt token it gving fetal error as i follow the documentation but its giving error  the error is commented below

### ISSUE THREAD

**Issue by mqnabeel** [web-token/jwt-framework#331]

**Comment by mqnabeel** [comment]
Fatal error: Uncaught RuntimeException: Unable to load and decrypt the token. in D:\xamp\htdocs\projecttwo\vendor\web-token\jwt-framework\src\Component\Encryption\JWELoader.php:107 Stack trace: #0 D:\xamp\htdocs\projecttwo\vendor\web-token\jwt-framework\src\Component\Encryption\JWELoader.php(82): Jose\Component\Encryption\JWELoader->loadAndDecryptWithKeySet('eyJhbGciOiJBMjU...', Object(Jose\Component\Core\JWKSet), NULL) #1 D:\xamp\htdocs\projecttwo\dec.php(171): Jose\Component\Encryption\JWELoader->loadAndDecryptWithKey('eyJhbGciOiJBMjU...', Object(Jose\Component\Core\JWK), NULL) #2 {main} thrown in D:\xamp\htdocs\projecttwo\vendor\web-token\jwt-framework\src\Component\Encryption\JWELoader.php on line 107

**Comment by Spomky** [comment]
Hi,

Please, would you mind to copy and paste the source code you used and that lead to that exception?

Many thanks.
Regards.
