### ISSUE TITLE
JWEBuilder with alg RSA-OAEP-256  Always time out to encrypt 

### ISSUE THREAD

**Issue by ierover** [web-token/jwt-framework#340]
Runninng Result: 
Maximum execution time of 30 seconds exceeded

**Comment by Spomky** [comment]
When using RSA encryption algorithms, it is highly recommended to enable either GMP or BCMatch extension.
Please make sure you installed one of these extensions.

**Comment by ierover** [comment]
Work fine after BCMatch installed. 
Thank you!
