### ISSUE TITLE
Problem after upgrade to symfony 6.1

### ISSUE THREAD

**Issue by temp** [web-token/jwt-framework#349]
web-token/jwt-bundle: v3.0.4

**Description**
I'm experiencing this error when calling bin/console (or any other entry point) in dev mode:
```
The class "Symfony\Component\Serializer\Debug\TraceableEncoder" neither implements "Symfony\Component\Serializer\Normalizer\NormalizerInterface" nor "Symfony\Component\Serializer\Normalizer\DenormalizerInterface".
```

**How to reproduce**
Update to symfony 6.1, call bin/console in dev mode

**Possible Solution**
I guess something changed about symfony-serializers normalizers and encoders.
`\Jose\Bundle\JoseFramework\Serializer\JWESerializer` and `\Jose\Bundle\JoseFramework\Serializer\JWSSerializer` are both at the same time, normalizer and encoder. I made a test, and split both files into a seperate JW(E|S)SerializerNormalizer and JW(E|S)SerializerDecoder, and registered all 4 with the respective tag in `\Jose\Bundle\JoseFramework\DependencyInjection\Compiler\SymfonySerializerCompilerPass`, and it worked without errors gain.

**Comment by Spomky** [comment]
Hi,

This should be fixed with the latest version `3.0.5`.
Can you confirm?

**Comment by temp** [comment]
@Spomky works like a charm now, thanks!

**Comment by Spomky** [comment]
Perfect 🤠. All credits go to @mdeboer!
