### ISSUE TITLE
Shared secret fails to be computed from Rx sKey and Tx pKey on an ECDH-ES+A256KW

### ISSUE THREAD

**Issue by HDNAdministrator** [web-token/jwt-framework#354]
**Version(s) affected**: 3.0.0

**Description**
The  ECDHES.calculateAgreementKey() (line 115) fails when decryptering.

**How to reproduce**

\<?php
	declare(strict_types=1);

	require_once('vendor/autoload.php');

	use Jose\Component\Checker\AlgorithmChecker;
	use Jose\Component\Checker\HeaderCheckerManager;
	use Jose\Component\Core\AlgorithmManager;
	use Jose\Component\Encryption\JWEBuilder;
	use Jose\Component\Encryption\Algorithm\ContentEncryption\A256CBCHS512;
	use Jose\Component\Encryption\Algorithm\KeyEncryption\A256KW;
	use Jose\Component\Encryption\Algorithm\KeyEncryption\ECDHESA256KW;
	use Jose\Component\Encryption\Compression\CompressionMethodManager;
	use Jose\Component\Encryption\Serializer\JWESerializerManager;
	use Jose\Component\Encryption\JWEDecrypter;
	use Jose\Component\Encryption\JWELoader;
	use Jose\Component\Encryption\JWETokenSupport;
	use Jose\Component\Encryption\Serializer\CompactSerializer;
	use Jose\Component\KeyManagement\JWKFactory;

	try {
		$jwkB = JWKFactory::createOKPKey('X25519');

		print("\nBOB ------------------------------------------------------------------------\n\n");
		var_dump($jwkB);
		print("\nBOB ------------------------------------------------------------------------\n\n");

		$jwt = sentByAlice($jwkB->toPublic());

		print("\nALICE ----------------------------------------------------------------------\n\n");
		var_dump($jwt);
		print("\nBOB ------------------------------------------------------------------------\n\n");

		receivedByBob($jwt, $jwkB);
	} catch (\Throwable $th) {
		echo $th->getMessage();
	}

	function sentByAlice(Jose\Component\Core\JWK $jwb): string {
		$payload = json_encode([
			'iat' => time(),
			'nbf' => time(),
			'exp' => time() + 3600,
			'iss' => 'ISS',
			'aud' => 'AUD',
		]);

		$keyManager = new AlgorithmManager([new ECDHESA256KW()]);

		$contentManager = new AlgorithmManager([new A256CBCHS512()]);

		$compressionManager = new CompressionMethodManager();

		$jweBuilder = new JWEBuilder($keyManager, $contentManager, $compressionManager);

		$jwe = $jweBuilder
			->create()
			->withPayload($payload)
			->withSharedProtectedHeader(['alg' => 'ECDH-ES+A256KW', 'enc' => 'A256CBC-HS512'])
			->addRecipient($jwb)
			->build();

		var_dump($jwe);

		$serializer = new CompactSerializer();

		return $serializer->serialize($jwe, 0);
	}

	function receivedByBob(string $jwt, Jose\Component\Core\JWK $jwb) {
		$serializer = new CompactSerializer();

		$serializerManager = new JWESerializerManager([$serializer]);

		$jwe = $serializerManager->unserialize($jwt);

		$keyManager = new AlgorithmManager([new ECDHESA256KW()]);

		$contentManager = new AlgorithmManager([new A256CBCHS512()]);

		$compressionManager = new CompressionMethodManager();

		$jweDecrypter = new JWEDecrypter($keyManager, $contentManager, $compressionManager);

		$success = $jweDecrypter->decryptUsingKey($jwe, $jwb, 0);

		var_dump($success);

		// var_dump($jwe);
	}
\?>

**Possible Solution**
Is it possible that the OKPKey creation implementation in JWKFactory is different from ECDHES one

**Additional context**

**Comment by Spomky** [comment]
Is it related to #356?
Looks like there is an issue with OKP keys.
Or does it come from modifications done on the sodium extension?
TBC

**Comment by HDNAdministrator** [comment]
I think they are related. Didn't though of it at the time.

**Comment by Spomky** [comment]
This is fixed in `v3.0.7`.
The issue was from the way the X25519 private key is generated.
