### ISSUE TITLE
Add ECDH-SS

### ISSUE THREAD

**Issue by HDNAdministrator** [web-token/jwt-framework#355]
**Description**
Add the ECDH-SS variant 

**Example**
[JWEBuilder.txt](https://github.com/web-token/jwt-framework/files/9240479/JWEBuilder.txt)
[ECDHSS.txt](https://github.com/web-token/jwt-framework/files/9240549/ECDHSS.txt)
[ECDHSSA256KW.txt](https://github.com/web-token/jwt-framework/files/9240560/ECDHSSA256KW.txt)
[ECDHSSAESKW.txt](https://github.com/web-token/jwt-framework/files/9240568/ECDHSSAESKW.txt)

The 1st iteration of the implementation was attached and are 4 files: the modified JWEBuilder and the ECDHSS, ECDHSSAESKW and ECDHSSA256KW, all modifed version of the ES variant.
They are all PHP but safed as TXT so that they could be included and you can find notes/comments in the files.

**Comment by Spomky** [comment]
Many thanks. ECDH-SS is definitely something I wanted to integrate.
You are right, contrary to the ECDH-ES variant where an ephemeral key is created, it requires extra modifications to retrieve the sender key.

**Comment by HDNAdministrator** [comment]
> Many thanks. ECDH-SS is definitely something I wanted to integrate. You are right, contrary to the ECDH-ES variant where an ephemeral key is created, it requires extra modifications to retrieve the sender key.

You are wellcome.
Apart from JWEBuilder, NestedTokenBuilder and NestedTokenLoader the adaptation from ES to SS seems quite straightforward but php is not my strongest language.

**Comment by Spomky** [comment]
Hi @HDNAdministrator,

Changes are going to be addressed through #366.
You can start testing it with the branch https://github.com/web-token/jwt-framework/tree/features/ecdh-ss
