### ISSUE TITLE
Try symplify instead of gitsplit

### ISSUE THREAD

**Issue by szepeviktor** [web-token/jwt-framework#398]
### Description

It is a better tool.

https://github.com/symplify/monorepo-builder 👀 

That is all.

**Comment by Spomky** [comment]
Hi @szepeviktor,

This looks good to me.
I will give it a try and see how to use it here.
Many thanks.

**Comment by szepeviktor** [comment]
Dear @stalebot, please let Florent think!

**Comment by Spomky** [comment]
Even though this tool is very interesting, gitsplit lite is sufficient for this project. The only feature I miss is signing sub repositories, but I haven't seen that feature on this tool
I prefer to leave the configuration as it is for the moment.
Thanks

**Comment by szepeviktor** [comment]
> sufficient

Me (a perfectionist) is not able to comprehend that word 🙃 Sorry.

**Comment by Spomky** [comment]
hummm. OK I integrated it here. The CI/CD is broken, but it is related to another workflow.

**Comment by szepeviktor** [comment]
# 😲 

What??

**Comment by szepeviktor** [comment]
This config file looks beautiful!! ❤️ 
https://github.com/web-token/jwt-framework/blob/3.2.x/monorepo-builder.php

(meaning readable and sustainable)

**Comment by Spomky** [comment]
I cannot figure out what is going on with the configuration I use here.
The github action is called as expected, but tags are not propagated. It looks like I missed something, but what?
When a milestone is closed (e.g. 3.2.5), the tag is correctly added on the monorepo. This is done by [this action](https://github.com/web-token/jwt-framework/actions/runs/5024178870) (+ other cool stuff like branch/milestone creation and merge-up PRs). But when the split action is closed, tags are missing.
Any thoughts on this?

**Comment by szepeviktor** [comment]
@tomasvotruba Could you help? I've never seen a monorepo from the inside.

**Comment by TomasVotruba** [comment]
Hey, I don't use it much latelly.

But here is a Github action to kick off: https://github.com/danharrin/monorepo-split-github-action

**Comment by Spomky** [comment]
Closing for now. The whole split system will be revised in the next minor release.
