### ISSUE TITLE
Symfony 6.1 or 6.0

### ISSUE THREAD

**Issue by igor-popryadukhin** [web-token/jwt-framework#406]
### Description

Hi
I'm sorry, I do not speak English well.
I think the versions should be equal

I can't install package for Symfony 6.1

![image](https://user-images.githubusercontent.com/48174353/192075251-91f9f773-19d1-43b3-9890-ddedbae1e365.png)

**Comment by Spomky** [comment]
Hi,

Can you copy/paste the error in your terminal?
Also, it is not recommended to install the whole framework buk only the components you need i.e. `composer require web-token/jwt-bundle`, and the algorithms or header/claims validators

**Comment by Spomky** [comment]
The dependencies clearly include SF 5.4 or 6.x (see web-token/jwt-framework).
The dependency you highlighted is related to the dev env.
Closing as not related to the package itself, but undoubtedly induced by one of your dependencies.
