### ISSUE TITLE
Encrypted token creation is not valid?

### ISSUE THREAD

**Issue by CyberMew** [web-token/jwt-framework#409]
### Version(s) affected

3.1.2

### Description

I followed the JWE Creation guide and its similar except the algorithms used is A256GCMKW with A256GCM. I’m unable to validate it.

It is able to encrypt and decrypt the payload by itself, but when I tried a variety of other libraries and none can decrypt this library’s JWE, and this library’s JWE can’t decrypt the JWEs made by other libraries. I tried a few libraries of different platforms and they all can encrypt and decrypt JWEs made by/for each other. 

Is it possible to look further into this combination? Or is there something I am missing from the guide and using it wrongly?

### How to reproduce

Just follow the JWE creation document and set the strings for `alg` to `A256GCMKW` and `enc` to `A256GCM`.

**Comment by Spomky** [comment]
Hi,

Thank you for reporting this issue.
Would you mind to add an example. In addition, what are the other libraries you tried.
This library is fully compliant with the specification and it works fine with e.g. [Nimbus JOSE]([Nimbus JOSE+JWT](http://connect2id.com/products/nimbus-jose-jwt)), which is a Java library. But there be a bug somewhere and I need to investigate.

Many thanks.
Regards.
