### ISSUE TITLE
Return value must be of type AESKW\Wrapper, AESKW\A128KW returned

### ISSUE THREAD

**Issue by faizan-shk** [web-token/jwt-framework#411]
### Version(s) affected

3.x

### Description

 **TypeError: Jose\Component\Encryption\Algorithm\KeyEncryption\A128KW::getWrapper(): Return value must be of type AESKW\Wrapper, AESKW\A128KW returned**

Previously we were working with jwt 2.x and everything was working fine however we were using **Jose\Easy** component in our codebase.

Now after upgrading to jwt 3.x we have also done changes w.r.t deprecated **Jose\Easy** component however for **A128KW, A192KW, A256KW** JWE Encryption we are getting the above error.

This is mainly caused due to file `src/EncryptionAlgorithm/KeyEncryption/AESKW/AESKW.php:24` **$this->getWrapper()** function where return type **AESKW\Wrapper** is expected however **AESKW\A128KW** or **AESKW\A192KW** or **AESKW\A256KW** is returned.

As per our initial investigation a quick fix would be to remove return type from `src/EncryptionAlgorithm/KeyEncryption/AESKW/AESKW.php:42` **getWrapper** function and corresponding extended classes i.e **A128KW, A192KW, A256KW**.

Please suggest if this is an actual issue or something we need to do from our end!

### How to reproduce

Upgrading from 2.x to 3.1.x and creating JWE-A128KW Algorithm

**Comment by faizan-shk** [comment]
@Spomky can you please check the above issue on priority as we are blocked for our release!

**Comment by faizan-shk** [comment]
Maybe fixed by https://github.com/web-token/jwt-framework/pull/412

**Comment by Spomky** [comment]
The `AxxxKW` classes implement `Wrapper` interface e.g. https://github.com/Spomky-Labs/aes-key-wrap/blob/v7.0.0/src/A256KW.php#L7
I do not see any reason for this to fail. Can you make sure the `web-token/jwt-encryption-algorithm-aeskw` package is installed?

**Comment by faizan-shk** [comment]
Yes @Spomky the web-token/jwt-encryption-algorithm-aeskw is installed however I guess were some commits behind for spomky/aes-key-wrap once we updated it the issue was resolved!

**Comment by Spomky** [comment]
Excellent! Many thanks for confirming everything is fine.
Regards.
