### ISSUE TITLE
fgrosse/phpasn1 is abandoned

### ISSUE THREAD

**Issue by magentox** [web-token/jwt-framework#416]
### Description

Just reporting:
This package is abandoned and no longer maintained. No replacement package was suggested.

**Comment by jdreesen** [comment]
#415

**Comment by Spomky** [comment]
Hi,

This dependency is replaced by spomky-labs/pi-framework.
Thes should be fixed since 3.1.3.

**Comment by Spomky** [comment]
Please use `3.1.4`. This dependency is now gone.
Regards.
