### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by juggernautsei** [web-token/jwt-framework#439]
Maximum execution time of 30 seconds exceeded in vendor/brick/math/src/Internal/Calculator/NativeCalculator.php on line 406. This is the error that is thrown when I run this code.

     use Jose\Component\Core\AlgorithmManager;
    use Jose\Component\Core\JWK;
    use Jose\Component\Signature\Algorithm\RS256;
    use Jose\Component\Signature\JWSBuilder;

    $algorithmManager = new AlgorithmManager([
        new RS256(),
    ]);

    $keyFile = dirname(__FILE__, 6) . "/sites/RsaPrivateKey.pk";
    $contents = file_get_contents($keyFile);

    use Jose\Component\KeyManagement\JWKFactory;

    $key = JWKFactory::createFromKeyFile(
        $keyFile, // The filename
        null,                   // Secret if the key is encrypted, otherwise null
        [
            'use' => 'sig',         // Additional parameters
        ]
    );

    echo "done";
    $jwsBuilder = new JWSBuilder($algorithmManager);

    // The payload we want to sign. The payload MUST be a string hence we use our JSON Converter.
    $payload = json_encode([
        'exp' => time() + 3600,
        'iss' => 'My service',
        'aud' => 'jitsi',
    ]);
    

    $jws = $jwsBuilder
        ->create()                               // We want to create a new JWS
        ->withPayload($payload)                  // We set the payload
        ->addSignature($key, ['alg' => 'RS256']) // We add a signature with a simple protected header
        ->build();                               // We build it

    use Jose\Component\Signature\Serializer\CompactSerializer;

    $serializer = new CompactSerializer(); // The serializer

    $token = $serializer->serialize($jws, 0); // We serialize the signature at index 0 (we only have one signature).

    var_dump($token);

How do I get this to work?

**Comment by Spomky** [comment]
Hi,

First of all, many thanks for supporting this library! I really appreciate!
Regarding the timeout error and considering you are using an RSA-based algorithm (RSxxx), can you make sure either GMP or BCMATH extension is installed. These extensions are not mandatory, but will drastically increase the RSA signature process when available.

**Comment by clemlatz** [comment]
Hi there,

Just wanted to say that I encountered the same problem than @juggernautsei with my PHP dev environnement and installing the BCMATH extension solved it for me. 

As I'm using docker I had to add `RUN docker-php-ext-install bcmath` to my Dockerfile and rebuild the image.

So thanks to you @Spomky!

**Comment by juggernautsei** [comment]
I did find a solution where the kernel that my Ubuntu was built on did not include bcmath. However, when I followed the instructions to remove and rebuild it killed my Apache server.  I switched to an FHIR-based JWT that worked for my build.

**Comment by Spomky** [comment]
Closing as answered.
