### ISSUE TITLE
Any interest in providing a Laravel package?

### ISSUE THREAD

**Issue by remipelhate** [web-token/jwt-framework#440]
### Description

Hi there!

I was wondering, since there's a Symphony bundle, if there is any interest in providing a package for Laravel (as a sub repository) as well? A lot can be solved already with the Symphony bundle, however, I think we could improve the DX by:
- Automatically registering commands to Laravel's console kernel (should work with the provided Symphony commands out of the box)
- Generating keys from a config file spec
- Automatically registering a route to the JWKSet

I would be more than happy to help out. If there is no interest in adding this to the framework, I recon this could be a standalone package.

Cheers!

**Comment by Spomky** [comment]
Hi,

> I recon this could be a standalone package.

Actually, this is more or less what I have in mind. This includes the Symfony bundle that will be removed from the repository.
It adds a lot of dependencies and I would like to keep it as thin as possible.
Moreover, the Symfony bundle (and I guess this is the same for a Laravel package) does not evolves tha much and it goes from one version to another whitout any changes. So keeping such package in this repository has no benefits.

**Comment by remipelhate** [comment]
I kinda had the same feeling and I agree. But as the Symfony bundle was included, I thought it was worth to ask the question :) Thanks for your feedback!

**Comment by vcampitelli** [comment]
Hi there, sorry to dig an old post out but I had to add support to a Laravel app so I created [this lib](https://github.com/FusionAuth/fusionauth-laravel-jwt-auth-webtoken-provider/) which adds `web-token/jwt-framework` to the well-known [`tymon/jwt-auth`](https://github.com/tymondesigns/jwt-auth) and I'd love your input there @Spomky.
