### ISSUE TITLE
Accept Non-URL-Safe Base64 keys

### ISSUE THREAD

**Issue by gam04** [web-token/jwt-framework#450]
### Description

Thank you for this awesome project, I really love all the tools available, they have been a great help to me.

I'm not sure if the following is a issue, expected behaviour or feature request. Using the key in this code the following exception is thrown :

```
 Uncaught RangeException: Base64::decode() only expects characters in the correct base64 alphabet
```

Maybe it's due to a non-url-safe base64 string in the key.

Code:
```php
<?php

// The algorithm manager with the HS256 algorithm.
$algorithmManager = new AlgorithmManager([
    new HS256(),
]);

// Our key.
$jwk = new JWK([
    'kty' => 'oct',
    // ----------->  is this a Non-URL-Safe base64 string  ??   because of '/' ?? <------------
    'k' => 'caAbB0dek1Th/eQhLt2xMRP01i3tDCwYg3fa0vcLvT0=',
]);

// We instantiate our JWS Builder.
$jwsBuilder = new JWSBuilder($algorithmManager);

// The payload we want to sign. The payload MUST be a string hence we use our JSON Converter.
$payload = json_encode([
    'iat' => time(),
    'nbf' => time(),
    'exp' => time() + 3600,
    'iss' => 'My service',
    'aud' => 'Your application',
]);

$jws = $jwsBuilder
    ->create()                          
    ->withPayload($payload)  
    ->addSignature($jwk, ['alg' => 'HS256']) // throws : RangeException: Base64::decode() only expects characters in the correct base64 alphabet
    ->build();     
```
I used the above key in the [`jose-node`](https://developer.cisco.com/codeexchange/github/repo/cisco/node-jose/)  package for Javascript with no problem, so i not sure if this is a issue or a bad practice.

**Comment by Spomky** [comment]
Hi,

I am happy the library helps you.
As per the [specification](https://www.rfc-editor.org/rfc/rfc7518.html#section-6.4.1), the expected encoding  for the `k` value is Base64Url.

As a temporary fix, with `rtrim(strtr($data, '+/', '-_'), '=');`, your data can be convert. 
But the best would be a fix from the other library your are using.

**Comment by gam04** [comment]
Hi @Spomky.

Thank you so much for the quick response.
I will close the issue since I am clear now about the specification for the 'k' field.
