### ISSUE TITLE
Signing JWT with private key

### ISSUE THREAD

**Issue by AamirFintech** [web-token/jwt-framework#461]
### Description

Is there any way to sign JWT with a signing key or private key using this library?

### Example

here is an example to sign jwt with private key

https://github.com/nov/jose-php

$jwt->sign($privateKey, $algorithm)->toString();

**Comment by Spomky** [comment]
Hi @AamirFintech

> Is there any way to sign JWT with a signing key or private key using this library?

Yes, it is possible and explained in https://web-token.spomky-labs.com/

**Comment by AamirFintech** [comment]
Can you point me to the exact path, What I found we can do with JWKS set? 
https://web-token.spomky-labs.com/the-components/signed-tokens-jws/jws-creation

I want to do something like this. 

```
`require 'vendor/autoload.php';

use Jose\Component\Core\AlgorithmManager;
use Jose\Component\Core\JWK;
use Jose\Component\Signature\Algorithm\RS256;
use Jose\Component\Signature\JWSBuilder;
use Jose\Component\Signature\Serializer\CompactSerializer;

// Load the private key from the PEM file
$privateKey = openssl_pkey_get_private('file://path/to/private_key.pem');

// Create an algorithm manager and register RS256 algorithm
$algorithmManager = new AlgorithmManager([
    new RS256(),
]);

// Create a JWK (JSON Web Key) from the private key
$jwk = JWK::createFromKey($privateKey);

// Create a JWS (JSON Web Signature) builder
$jwsBuilder = new JWSBuilder($algorithmManager);

// Set the claims (payload) for the JWT
$payload = [
    'iss' => 'issuer',
    'aud' => 'audience',
    'exp' => time() + 3600,
    'key' => 'value'
];

// Sign the JWT with the private key
$jws = $jwsBuilder
    ->create()
    ->withPayload(json_encode($payload))
    ->addSignature($jwk, ['alg' => 'RS256'])
    ->build();

// Serialize the JWT into a compact string format
$serializer = new CompactSerializer();
$jwt = $serializer->serialize($jws, 0);

// Output the signed JWT
echo $jwt;`
```

**Comment by Spomky** [comment]
What you are doing looks good. I do not understand the trouble you may have.
I close this issue, but feel free to share additional context information if deemed necessary.
