### ISSUE TITLE
How to get thumbprint

### ISSUE THREAD

**Issue by lyrajane09** [web-token/jwt-framework#465]
I just want to know how to get the thumbprint from this code? thanks for answering my question

`public function generateDPOP(){
        $signingKeyPassphrase = config('services.singpass.signing_key_passphrase');
        
        // import signature signing key
        $signingKey = JWKFactory::createFromKeyFile("file://" . base_path(config('services.singpass.signing_key')) , $signingKeyPassphrase);
        $algorithmFactory = new AlgorithmManagerFactory();
        // initiate the algorithm aliases
        $algorithmFactory->add('ES256' , new ES256());
        $algorithmFactory->add('ES384' , new ES384());
        $algorithmFactory->add('ES512' , new ES512());

        // load all the support signature algorithm based on singpass API openid configuration
        $algorithmFactory->create(["ES256", "ES384", "ES512"]);

        $algorithmManager = new AlgorithmManager($algorithmFactory->all());

        $jwsBuilder = new JWSBuilder($algorithmManager);
        // JWT issue timestamp
        $issuedAt = now();
        //build jwt
        $jwt = $jwsBuilder->create()
            ->withPayload(json_encode([
                'htu'   =>  'https://sandbox.api.myinfo.gov.sg/com/v4/token',
                'htm'   =>  'POST',
                'jti'   =>  bin2hex(openssl_random_pseudo_bytes(10)), // 20 chars
                'iat' => $issuedAt->unix(),
                'exp' => $issuedAt->addMinutes(5)->unix() // 5 MINS EXPIRATION
            ])) // insert claims data
            ->addSignature($signingKey, [
                'typ' => 'dpop+jwt', 
                'alg' => 'ES256', 
                'jwk' => json_encode([
                    "kty" => "EC",
                    "crv" => "P-256",
                    "x"   => "_AlQrWzTPkMCBle0m_ZLqYuQmtDrSIFcWniPukkzYbc",
                    "y"   => "Broz9_vivuhNddCqofu4TIH1EA_U2J0kz5mTx78DP_I",
                    "kid" => "acme_verification_key",
                    "use" => "sig",
                    "alg" => "ES256"
                ])
            ]) // sign it and add the JWS protected header
            ->build();
       
        $serializer = new CompactSerializer(); // The serializer

        // generate base64 encoded JWT
        $dpop = $serializer->serialize($jwt, 0);
        // dd($this->sha1Thumbprint());
    
        return  $dpop;
    }`

**Comment by Spomky** [comment]
Hi,

The question is not really clear. What thumbprint are you waiting for?
If it is the one for the key, there is a convenient method: https://web-token.spomky-labs.com/the-components/key-jwk-and-key-set-jwkset/key-management
For any other thumbprint, it is usually just a hash of the data with a given hashing function 'I can read sha-1 here).
