### ISSUE TITLE
Document "required" clock parameter

### ISSUE THREAD

**Issue by cookieguru** [web-token/jwt-framework#474]
### Description

#433 introduced [an annoying `E_USER_DEPRECATED` error](https://github.com/web-token/jwt-framework/pull/433/files#diff-a2bc63fe1cb9ed6a21f40fe459c2201d169b228bfb9dd582ab57ec9e91c39efbR26) in 3.2.0.  This new paramater:
* Is [not documented](https://web-token.spomky-labs.com/the-components/claim-checker?q=clock)
* Was not announced in [the release notes](https://github.com/web-token/jwt-framework/releases/tag/3.2.0)
* Is optional, but is noisy when omitted

I'll take responsibility for:
* My library that consumes `web-token/jwt-framework` requires `^3.1` but should be `~3.1`
* Slim 4's [default error handler](https://github.com/slimphp/Slim-Skeleton/blob/cc6edc206587ff35412961a66577ce23584fce5f/src/Application/Handlers/HttpErrorHandler.php#L64) appends deprecation notices to the existing payload.  So a successful API response that should return this:
```json
{"foo": "bar"}
```
is actually returning this:
```json
{"foo": "bar"}{
  "statusCode": 500,
  "error": {
    "type": "SERVER_ERROR",
    "description": "ERROR: Since web-token\/jwt-checker 3.2.0: The parameter \"$clock\" will become mandatory in 4.0.0. Please set a valid PSR Clock implementation instead of \"null\". on line 25 in file \/var\/www\/vendor\/symfony\/deprecation-contracts\/function.php."
  }
}
```
on *every* request.

This issue is to request documentation for the parameter, and/or provide an Upgrading guide in the repo

I'll save the debate on whether "you used to do 'nothing', but in the future you must do 'something'" qualifies as a _deprecation_ for a future ticket.

**Comment by cookieguru** [comment]
I'd also like to note that the error message doesn't provide the developer any information as to where the `$clock` parameter needs to be passed in.  In addition, the stack trace does not mention any file from this library.

**Comment by Spomky** [comment]
Hi @cookieguru,

I'm sorry for the inconvenience. The release note is automatically created when the milestone is closed.
Unfortunately it is completely empty for this release and I don't know the reasons as all changes are properly labeled.

Documentation for the latest minor releases is missing. I will take care of it and align the documentation with the last modification.
I don't know how the Slim framework handles deprecation notices, but it can certainly be sent in some other way than adding it to the response body.

**Comment by cookieguru** [comment]
Thanks for the reminder StaleBot; this is still an issue

**Comment by Spomky** [comment]
The documentation is now up to date and a [note is present](https://web-token.spomky-labs.com/the-components/header-checker#provided-header-checker-objects) for time-based parameter checkers.
Unfortunately, the release note cannot be changed.
I close the issue as I do not see any action for now, but feel free to reopen if deemed necessary.
