### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by bohanwood** [web-token/jwt-framework#490]
### Description

Symfony 7 has been released.

### Example

Update composer.json `^5.4|^6.0|^7.0`

**Comment by a-menshchikov** [comment]
Hi @Spomky 
Is there any plans about Symfony 7 support?

**Comment by Spomky** [comment]
Hi,
I will take care of it this week.
I do not see any difficulties to implement it in the minor 3.2.x version.

**Comment by Spomky** [comment]
Work done in branch 3.2.x. Will be tagged soon
