### ISSUE TITLE
Deprecation: Symfony 6.4

### ISSUE THREAD

**Issue by kiropowered** [web-token/jwt-framework#500]
### Version(s) affected

latest

### Description

Since symfony the following deprecation is triggered : 
Since symfony/serializer 6.3: "Jose\Bundle\JoseFramework\Serializer\JWSSerializer" should implement "DenormalizerInterface::getSupportedTypes(?string $format): array

### How to reproduce

Use symfony bundle in symfony 6.4 context

### Possible Solution

Implement getSupportedTypes method in Jose\Bundle\JoseFramework\Serializer\JWSSerializer

**Comment by Spomky** [comment]
Hi,

Can you indicate the exact version instead of `latest`?
Because this is [already implemented](https://github.com/web-token/jwt-framework/blob/3.2.x/src/Bundle/JoseFramework/Serializer/JWSSerializer.php#L36).

**Comment by kiropowered** [comment]
Hi, sorry it was 3.2.8 seems like it was fixed in 3.2.9(5 days ago), thank you

**Comment by Spomky** [comment]
Perfect 👌. Indeed it was introduced and tagged recently.
