### ISSUE TITLE
Disable data collectors in dev?

### ISSUE THREAD

**Issue by temp** [web-token/jwt-framework#502]
### Version(s) affected

3.2.8

### Description

Is there a way to disable the data collectors in dev?

### How to reproduce

For example composer install with APP_ENV=dev, it will trigger data collection.

**Comment by Spomky** [comment]
Hi 👋🏼,

There is no configuration option to disable the data collector.
I think this is a nice addition. Would you mind to create a PR for that?

Regards.

**Comment by Spomky** [comment]
Closing as not planned for now
