### ISSUE TITLE
InvalidArgumentException: decodeNoPadding() doesn't tolerate padding

### ISSUE THREAD

**Issue by glo71317** [web-token/jwt-framework#504]
### Version(s) affected

3.2.9

### Description

Some issue with happening during validating the input data and throwing InvalidArgumentException with new version.
when tried with 3.2.8 and other previous versions, we did not find any issue.

Might be some issue introduced in new version 3.2.9[](url)

### How to reproduce

In adobe commerce when we update this library with latest version we started getting InvalidArgumentException
If need the sample code to reproduce this with sample code then we have to work on.

I think some backward compatibility issue  which should be in patch version 3.2.9 because 3.2.8 is working fine for us.
if you needed anything from our end we will try to provide.

### Additional Context
<img width="851" alt="Screenshot 2024-01-18 at 4 41 19 PM" src="https://github.com/web-token/jwt-framework/assets/85922880/6fb06ab8-32b8-4d55-9223-1625ae3b213d">

_No response_

**Comment by Spomky** [comment]
Hi 👋🏼,

Just remove the extra `=` at the end of the [secret string](https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/testsuite/Magento/JwtFrameworkAdapter/Model/JwsManagerTest.php#L24).
Let me know if the exception is still there after the modification. Note that this error is the normal behavior, but was not throw in the last minor versions.
