### ISSUE TITLE
Rsa signing works too slow

### ISSUE THREAD

**Issue by CvekCoding** [web-token/jwt-framework#530]
### Version(s) affected

3.3

### Description

Hello.
I ran into a problem when creating tokens - the RSA signature takes an insanely long time to work, a few minutes. At the same time, other algorithms (I checked ES256) work fast. The problem is in the \Jose\Component\Core function\Util\RSAKey::populateBigIntegers. Very heavy mathematical operations are launched there, which take up all the time.

I am attaching my project with vanilla Symfony and a generated 4096 RSA key.
[jwt-token.tar.gz](https://github.com/web-token/jwt-framework/files/14422450/jwt-token.tar.gz)

### How to reproduce

1. Launch `docker-compose up -d`
2. `docker compose exec php bin/console lexik:jwt:generate-token test`

The project also contains es-signature, and it works blazing fast.

**Comment by Spomky** [comment]
Hi,

Have you installed GMP or BCMATH extension?
https://github.com/web-token/jwt-framework/blob/3e87ce132f6cbeb228b6d4d9ad105dce395458d8/src/Library/composer.json#L57

**Comment by CvekCoding** [comment]
Let me try...

**Comment by CvekCoding** [comment]
You are right, now it works.
I was sure that I had looked through all the hints in composer(

**Comment by CvekCoding** [comment]
Thanks for fast response
