### ISSUE TITLE
Newlines random based on environment

### ISSUE THREAD

**Issue by jasverix** [web-token/jwt-framework#568]
### Version(s) affected

4.x

### Description

When encoding or decoding RSA keys, the KeyConverter uses the PHP_EOL constant to add newlines. On Linux machines it works nice, but in other environments, it becomes "\r\n" which destroys the keys.

### How to reproduce

Try to load a valid key on a Windows machine.

### Possible Solution

Replace PHP_EOL with "\n".

**Comment by Spomky** [comment]
Fixed and tagged 3.4.4.
