### ISSUE TITLE
Symfony Bundle JWKS documentation incorrect

### ISSUE THREAD

**Issue by AlexLisenkov** [web-token/jwt-framework#587]
### Description

https://web-token.spomky-labs.com/v4.0/the-symfony-bundle/key-and-key-set-management/key-set-management-jwkset#distant-key-sets

Seems like the configuration has changed since version 4.

`request_factory` is not an option anymore
`client` needs to be of symfony and not psr

This causes two exceptions respectively:
```
Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "request_factory" under "jose.jku_factory". Available options are "client", "enabled".
```
```
TypeError: Jose\Component\KeyManagement\UrlKeySetFactory::__construct(): Argument #1 ($client) must be of type Symfony\Contracts\HttpClient\HttpClientInterface, Http\Client\Common\PluginClient given, called in [...]
```

Changing it to the symfony `symfony/http-client` and changing configuration works. But no caching is enabled by default.
```yaml
jose:
  jku_factory:
    enabled: true
    client: 'http_client'
```

Documentation needs change.

**Comment by Spomky** [comment]
Indeed, the documentation page is incorrect.
I propagated to changes.
Many thanks 👍🏽 .
