### ISSUE TITLE
Add Nested Tokens support

### ISSUE THREAD

**Issue by bwowk** [web-token/jwt-framework#65]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| **Feature request?**     | **yes**
| BC Break report?     | no
| RFC? / Specification | no
| Version              | 1.0

Please add support for Nested Tokens

**Comment by Spomky** [comment]
Nested tokens are already supported, but there is no convenient way to build/load them.
However those tokens can be easily created:

* Nested token creation:
    1. create a JWS as usual.
    2. create a JWE with the following header member: `cty`: `JWT`.
* Nested token loading
    1. try to decrypt the JWE
    2. if the JWE header contains the member `cty` with the value`JWT`, try to load the JWS in the payload.

I am working on [the JWSLoader and the JWELoader](https://github.com/web-token/jwt-framework/pull/62) that will ease the loading of the token. I may integrate a better solution to helpyou to deal with such tokens.

**Comment by Spomky** [comment]
Closing as PR in progress (see https://github.com/web-token/jwt-framework/pull/85)
If you have any remark, please comment in the PR discussion.

Thanks.

**Comment by Spomky** [comment]
Tagged `v1.1.0-beta1`; Will be marked as stable soon.
