### ISSUE TITLE
Issue with JWSVerifier

### ISSUE THREAD

**Issue by mikemirten** [web-token/jwt-framework#75]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no

Class ```Jose\Component\Signature\JWSVerifier``` is final and there is no JWSVerifier interface. This makes impossible to mock the class while testing a component has JWSVerifier as a dependency.

**Comment by Spomky** [comment]
Hi @mikemirten, thank you for reporting this.
This class and almost all classes of the project are final.
The point is that I do not understand why you want to mock a concrete class when you can easily instantiate it (just requires an algorithm manager).

**Comment by mikemirten** [comment]
Because i'm writing a unit test. It means my class should be tested in an artificial environment of mocked dependencies. Otherwise it would be an integration test and i would not be sure, a bug i caught belongs to my class or to a dependency.

**Comment by mikemirten** [comment]
Similar problem with ```Jose\Component\Signature\Serializer\JWSSerializer```. Though it is an interface but ```unseialize()``` method it returns an instance of ```Jose\Component\Signature\JWS``` which is a final class. So it makes impossible to mock the serializer itself.

**Comment by mikemirten** [comment]
Just took a look at tests of the library. You don't using mocks anywhere, only a real instances. So in fact you don't have any unit tests, but only an integration ones. Your architecture just does not allows to write unit tests. And, with all respect, but it means only one: there is something wrong with architecture.

I don't want to looks like a guy only criticizing.  How about, if i would help you to fix these problems ?

**Comment by Spomky** [comment]
Hi @mikemirten,

As I said, almost all classes are final. At the moment, I don't plan to remove that keyword.
The tests I wrote don't mock anything because I don't have to.
From my point of view, the use of

```php
$verifier = new JWSVerifier(
    AlgorithmManager::create([new TheAlgorithmYouWantToUse()])
);
```

is not more complicated and has the same result as

```php
$verifier = $this->createMock(JWSVerifier::class);
$verifier->method('someMethod')
    ->willReturn('foo-bar');
```

You don't need any certificate. For unit testing of your classes you can use the `none` algorithm with the key `JWK::create(['kty' =>'none'])` and you're done.

Can you please share with me an example of class you want to test?

**Comment by mikemirten** [comment]
Thank you for advice with none-algorithm, it simplifies situation a bit.

Yes, i've noticed what almost all classes are final and it would not be a problem if all final classes would have interfaces.

About unit testing, i've explained already, if you're using real instances it is not a unit-testing, but rather integration.

This is a shortened version of the class:
```php
class JWTAuthenticator extends AbstractGuardAuthenticator
{
    protected $serializer;
    protected $verifier;

    public function __construct(JWSSerializer $serializer, Verifier $verifier)
    {
        $this->serializer = $serializer;
        $this->verifier   = $verifier;
    }

    public function getCredentials(Request $request)
    {
        $content = $this->extractAuthContent($request);
        $token   = $this->serializer->unserialize($content);

        if (! $this->verifier->verify($token)) {
            throw new SignatureVerificationFailedException();
        }

        $payload = $token->getPayload();
        $claims  = json_decode($payload, true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new InvalidAuthenticationHeaderException();
        }

        return new Token($claims);
    }
}
```
That is a symfony guard authenticator.

Verifier is a facade wraps JWSVerifier. Serializer is an interface so there is no problem with mocking of serializer itself, but there is still problem with JWS which cannot be mocked.

This is a test:
```php
class JWTAuthenticatorTest extends TestCase
{
    public function testGetCredentials()
    {
        $serializer = $this->createMock(JWSSerializer::class);
        $verifier   = $this->createMock(Verifier::class);

        $jws = JWS::create('{"username": "john.doe"}');

        $request = $this->createMock(Request::class);
        $request->headers = $this->createMock(HeaderBag::class);

        $request->headers->method('get')
            ->with('Authorization')
            ->willReturn('Bearer q1w2e3r4t5y');

        $serializer->expects($this->once())
            ->method('unserialize')
            ->with('q1w2e3r4t5y')
            ->willReturn($jws);

        $verifier->expects($this->once())
            ->method('verify')
            ->with($jws)
            ->willReturn(true);

        $authenticator = new JWTAuthenticator($serializer, $verifier);
        $token = $authenticator->getCredentials($request);

        $this->assertInstanceOf(Token::class, $token);
        $this->assertSame('john.doe', $token->getUsername());
    }
}
```
I don't want to test how serializer unserializes and how verifier verifies, they are abstract for this case, so i using mocks (usual practice with unit testing), i only want to test behaviour of the authenticator itself.

**Comment by Spomky** [comment]
What you say is legit to me. A unit test should not go outside of the class/method you want to test.
It may be possible that a test fails because of the component your are using and not because of a bug in your class.
It looks like there is no choice but adding interfaces. I will try to add these interfaces for the next minor release as there is no BC break here.
Hoping it will help you.

**Comment by Spomky** [comment]
As it induces lot of method signature changes, I have to postpone the integration of these interfaces.
Will be added to the next major release.

**Comment by Spomky** [comment]
Closing as classes are not final anymore (starting from v1.1 to be release soon).

**Comment by Spomky** [comment]
Tagged `v1.1.0-beta1`; Will be marked as stable soon.
