### ISSUE TITLE
Proposal: Allow definition of required claims and headers

### ISSUE THREAD

**Issue by timrourke** [web-token/jwt-framework#89]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no

Currently, the HeaderCheckerManager will perform validation on a header value _only_ if that header is present in the token. I believe it would improve security to enforce a rule that tokens my application consumes must have a certain set of header and payload claims present. For example, I would like to specify that any token I consume _always_ has a `kid` header claim present. This is _in addition to_ validating the `kid` header's _value_.

One option I considered was to throw an exception if `array_key_exists` is falsey [here](https://github.com/web-token/jwt-framework/blob/v1.0/src/Component/Checker/HeaderCheckerManager.php#L137), but I suspect that would complicate things for folks who are using valid tokens whose claims might vary from use to use.

An alternative would be to add a new kind of header and payload validation manager, wherein a user could specify a list of protected, unprotected, and/or payload claims they expect to be present on any token, something to the effect of:

```php
$requiredProtectedHeaders = [
    'kid',
];

$requiredUnprotectedHeaders = [];

$requiredProtectedClaims = [
    'sub',
    'required-custom-claim-one',
    'required-custom-claim-two',
];

$requiredClaimPresenceChecker = RequiredClaimPresenceCheckerManager::create(
    $requiredProtectedHeaders,
    $requiredUnprotectedHeaders,
    $requiredProtectedClaims
);

$requiredClaimPresenceChecker->check($token); // $token being, for example, a JWS instance
```

What do you think about this idea? If you agree that this might be useful, would you prefer that a required claim checker for the payload be a separate object from the required header claim checker?

If you think this is a reasonable idea, I would be happy to open a pull request to begin work on this. In the mean time, I can resort to validating "required" claims more manually using your toolset in my application.

Thanks!

**Comment by Spomky** [comment]
Nice feature!

Another way could by to add an interface (let say `MandatoryClaim`/`MandatoryHeader`) with a method `isMandatory(): bool`.
The checker manager will check the presence of the claim/header if the checker implement that interface.

This can be part of the next minor release.

Many thanks.

**Comment by Spomky** [comment]
Merged. Will be tagged `v1.1.0` soon.

**Comment by Spomky** [comment]
Tagged `v1.1.0-beta1`; Will be marked as stable soon.
