### ISSUE TITLE
Proposal: ORM to test

### ISSUE THREAD

**Issue by francescobianco** [web-token/jwt-framework#9]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by Spomky** [comment]
Hi @francescobianco,

I am not sure your project can be integrated here and I don't want to add any other dependencies.
This framework is just an implementation of the JWT format ; it has nothing do do with MySQL.
